apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "voicecan.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "voicecan.labels" . | nindent 6 }}
