apiVersion: v1
kind: Service
metadata:
  name: {{ include "voicecan.name" . }}
  labels:
    {{- include "voicecan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "voicecan.labels" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
