import { createHash, createHmac, randomUUID } from 'node:crypto';
import { createReadStream } from 'node:fs';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import {
  API_VERSION,
  OPEN_PLATFORM_PERMISSIONS,
  OPEN_PLATFORM_PERMISSION_TEMPLATES,
  normalizeOpenPlatformPermissions,
  type Device,
  type OpenPlatformApplication,
  type OpenPlatformChannel,
  type OpenPlatformPermission,
  type RecordingDownloadLink,
  type RecordingFile,
} from '@voicecan/contracts';
import { AccessDeniedError, requireGroup, requireGroupAdmin, requireScope, sqlGroupGuard, type AccessContext } from '@voicecan/access-control';
import type { ServerConfig } from './config.js';
import type { Database, SqlStatement } from './database.js';
import type { DeviceGateway } from './gateway.js';
import { encryptSecret, opaqueToken, tokenHash } from './security.js';
import type { S3ImmutableStorage } from './s3-storage.js';
import type { FilesystemStorage } from './storage.js';
import { validateWebhookUrl } from './events.js';
import { isIP } from 'node:net';
import { deviceCapabilities, mapPublicCommand, mapPublicRecording, recordingFilename } from './public-contract.js';

type Row = Record<string, unknown>;

export class OpenPlatformError extends Error {
  constructor(readonly statusCode: number, readonly code: string, message: string) { super(message); }
}

type ResolveAccess = (request: FastifyRequest, mutation?: boolean) => Promise<AccessContext>;
type Audit = (request: FastifyRequest, context: AccessContext, action: string, resourceType: string, resourceId?: string, groupId?: string, reason?: string) => Promise<void>;

export type OpenPlatformDependencies = {
  app: FastifyInstance;
  db: Database;
  config: ServerConfig;
  gateway: Pick<DeviceGateway, 'dispatchSync'>;
  storage: FilesystemStorage;
  s3Storage: S3ImmutableStorage | null;
  resolveAccess: ResolveAccess;
  audit: Audit;
};

function id(prefix: string): string { return `${prefix}_${randomUUID()}`; }
function now(): string { return new Date().toISOString(); }
function plus(milliseconds: number): string { return new Date(Date.now() + milliseconds).toISOString(); }
function bodyOf(request: FastifyRequest): Row {
  if (!request.body || typeof request.body !== 'object' || Array.isArray(request.body)) throw new OpenPlatformError(400, 'INVALID_REQUEST', 'JSON object required');
  return request.body as Row;
}
function requiredString(body: Row, key: string, maximum = 512): string {
  const value = body[key];
  if (typeof value !== 'string' || !value.trim() || value.length > maximum) throw new OpenPlatformError(400, 'INVALID_REQUEST', `${key} is required`);
  return value.trim();
}
function optionalString(body: Row, key: string, maximum = 512): string | null {
  const value = body[key];
  if (value === undefined || value === null || value === '') return null;
  if (typeof value !== 'string' || value.length > maximum) throw new OpenPlatformError(400, 'INVALID_REQUEST', `${key} is invalid`);
  return value.trim();
}
function integer(body: Row, key: string, fallback: number, minimum: number, maximum: number): number {
  const value = body[key] === undefined ? fallback : Number(body[key]);
  if (!Number.isSafeInteger(value) || value < minimum || value > maximum) throw new OpenPlatformError(400, 'INVALID_REQUEST', `${key} must be between ${minimum} and ${maximum}`);
  return value;
}
function stringArray(body: Row, key: string, maximum = 100): string[] {
  const value = body[key];
  if (!Array.isArray(value) || value.length > maximum || value.some((item) => typeof item !== 'string' || !item || item.length > 500)) throw new OpenPlatformError(400, 'INVALID_REQUEST', `${key} must be a string array`);
  return [...new Set(value as string[])];
}
function numberArray(body: Row, key: string, maximum = 100): number[] {
  const value = body[key];
  if (!Array.isArray(value) || value.length > maximum || value.some((item) => !Number.isSafeInteger(item) || Number(item) < 0 || Number(item) > 2)) throw new OpenPlatformError(400, 'INVALID_REQUEST', `${key} must contain recording attributes 0, 1, or 2`);
  return [...new Set(value.map(Number))];
}
function success<T>(reply: FastifyReply, data: T, status = 200): FastifyReply {
  return reply.code(status).send({ success: true, code: '', message: 'success', data, request_id: reply.request.id });
}
function parseJsonArray(value: unknown): string[] {
  try { const parsed = JSON.parse(String(value)); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : []; }
  catch { return []; }
}
function mapApplication(row: Row): OpenPlatformApplication {
  return {
    id: String(row.id), group_id: String(row.group_id), name: String(row.name), description: row.description === null ? null : String(row.description),
    environment: row.environment as OpenPlatformApplication['environment'], status: row.status as OpenPlatformApplication['status'],
    channels: parseJsonArray(row.channels_json) as OpenPlatformChannel[], owner_user_id: String(row.owner_user_id), version: Number(row.version),
    created_at: String(row.created_at), updated_at: String(row.updated_at),
  };
}
function mapDevice(row: Row): Device {
  return { id: String(row.id), display_name: row.display_name === null || row.display_name === undefined ? null : String(row.display_name), manufacturer: String(row.manufacturer), sn: String(row.sn), model: row.model === null ? null : String(row.model), hardware_version: row.hardware_version === null || row.hardware_version === undefined ? null : String(row.hardware_version), firmware_version: row.firmware_version === null ? null : String(row.firmware_version), group_id: String(row.group_id), ownership_epoch: Number(row.ownership_epoch), online: Boolean(row.online), last_seen_at: row.last_seen_at === null ? null : String(row.last_seen_at), created_at: String(row.created_at), updated_at: String(row.updated_at) };
}
function mapRecording(row: Row): RecordingFile {
  return mapPublicRecording(row);
}
function validPermissions(values: readonly string[]): OpenPlatformPermission[] {
  const allowed = new Set<string>(OPEN_PLATFORM_PERMISSIONS.map((permission) => permission.code));
  if (values.some((value) => !allowed.has(value))) throw new OpenPlatformError(400, 'INVALID_PERMISSION', 'One or more permissions are not in the permission catalog');
  return [...new Set(values)] as OpenPlatformPermission[];
}
function validChannels(values: readonly string[]): OpenPlatformChannel[] {
  const allowed = new Set(['rest', 'mcp_stdio', 'mcp_remote', 'webhook']);
  if (values.length === 0 || values.some((value) => !allowed.has(value))) throw new OpenPlatformError(400, 'INVALID_CHANNEL', 'One or more channels are invalid');
  return [...new Set(values)] as OpenPlatformChannel[];
}
function fingerprint(secret: string): string { return createHash('sha256').update(secret).digest('hex').slice(-12); }
function requestHash(value: unknown): string { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); }
function cursorEncode(createdAt: string, itemId: string): string { return Buffer.from(JSON.stringify([createdAt, itemId])).toString('base64url'); }
function cursorDecode(value: unknown): { createdAt: string; itemId: string } | null {
  if (value === undefined) return null;
  try { const parsed = JSON.parse(Buffer.from(String(value), 'base64url').toString()); if (!Array.isArray(parsed) || parsed.length !== 2 || parsed.some((item) => typeof item !== 'string')) throw new Error(); return { createdAt: parsed[0], itemId: parsed[1] }; }
  catch { throw new OpenPlatformError(400, 'INVALID_CURSOR', 'Cursor is invalid'); }
}
function sourceHash(request: FastifyRequest): string { return createHash('sha256').update(request.ip).digest('hex').slice(0, 24); }
function validCidrs(values: readonly string[]): string[] {
  for (const value of values) {
    const [address, prefixValue, extra] = value.split('/'); const family = isIP(address ?? ''); const prefix = prefixValue === undefined ? undefined : Number(prefixValue);
    if (extra !== undefined || !family || (prefix !== undefined && (!Number.isInteger(prefix) || prefix < 0 || prefix > (family === 4 ? 32 : 128)))) throw new OpenPlatformError(400, 'INVALID_IP_ALLOWLIST', `Invalid IP/CIDR rule: ${value}`);
  }
  return [...new Set(values)];
}

type ApplicationRole = 'owner' | 'developer' | 'viewer' | 'group_admin' | 'system_admin';
type ApplicationAccess = { application: Row; collaboratorRole: ApplicationRole };
const OAUTH_VIEWER_PERMISSIONS = new Set<OpenPlatformPermission>(['devices:read', 'commands:read', 'recordings:read', 'events:read']);

export async function resolveOAuthPrincipalPermissions(db: Database, userId: string, applicationId: string): Promise<{ role: ApplicationRole; scopes: Set<string> } | null> {
  const principal = await db.get<Row>(`SELECT u.role AS user_role,gm.role AS membership_role,c.role AS collaborator_role
    FROM users u JOIN open_platform_applications a ON a.id=? AND a.status='active'
    LEFT JOIN group_memberships gm ON gm.user_id=u.id AND gm.group_id=a.group_id AND gm.active=1
    LEFT JOIN application_collaborators c ON c.application_id=a.id AND c.user_id=u.id
    WHERE u.id=? AND u.disabled_at IS NULL`, [applicationId, userId]);
  if (!principal) return null;
  let role: ApplicationRole | null = null;
  if (principal.user_role === 'system_admin') role = 'system_admin';
  else if (principal.membership_role === 'group_admin') role = 'group_admin';
  else if (principal.membership_role === 'member' && ['owner', 'developer', 'viewer'].includes(String(principal.collaborator_role))) role = principal.collaborator_role as ApplicationRole;
  if (!role) return null;
  const applicationScopes = new Set((await db.all<{ permission: string }>('SELECT permission FROM application_permission_grants WHERE application_id=?', [applicationId])).map((item) => item.permission));
  return { role, scopes: role === 'viewer' ? new Set([...applicationScopes].filter((scope) => OAUTH_VIEWER_PERMISSIONS.has(scope as OpenPlatformPermission))) : applicationScopes };
}

export class OpenPlatformService {
  constructor(private readonly dependencies: Omit<OpenPlatformDependencies, 'app' | 'resolveAccess' | 'audit'>) {}

  private async applicationAccess(context: AccessContext, applicationId: string, minimum: 'viewer' | 'developer' | 'owner' = 'viewer'): Promise<ApplicationAccess> {
    if (context.actorType !== 'user') throw new AccessDeniedError();
    const application = await this.dependencies.db.get<Row>('SELECT * FROM open_platform_applications WHERE id=?', [applicationId]);
    if (!application) throw new AccessDeniedError();
    let role: ApplicationAccess['collaboratorRole'];
    if (context.isSystemAdmin) role = 'system_admin';
    else if (context.groupId === application.group_id && context.isGroupAdmin) role = 'group_admin';
    else {
      if (context.groupId !== application.group_id) throw new AccessDeniedError();
      const collaborator = await this.dependencies.db.get<{ role: 'owner' | 'developer' | 'viewer' }>('SELECT role FROM application_collaborators WHERE application_id=? AND user_id=?', [applicationId, context.actorId]);
      if (!collaborator) throw new AccessDeniedError();
      role = collaborator.role;
    }
    const rank = { viewer: 1, developer: 2, owner: 3, group_admin: 4, system_admin: 5 } as const;
    if (rank[role] < rank[minimum]) throw new AccessDeniedError();
    return { application, collaboratorRole: role };
  }

  async requireApplicationAccess(context: AccessContext, applicationId: string, minimum: 'viewer' | 'developer' | 'owner' = 'viewer'): Promise<Row> {
    return (await this.applicationAccess(context, applicationId, minimum)).application;
  }

  async requireApplicationPrincipal(context: AccessContext, applicationId: string, minimum: 'viewer' | 'developer' | 'owner' = 'viewer'): Promise<ApplicationAccess> {
    return this.applicationAccess(context, applicationId, minimum);
  }

  async listApplications(context: AccessContext): Promise<OpenPlatformApplication[]> {
    if (context.actorType !== 'user') throw new AccessDeniedError();
    const rows = context.isSystemAdmin
      ? await this.dependencies.db.all<Row>('SELECT * FROM open_platform_applications ORDER BY created_at DESC,id')
      : context.isGroupAdmin
        ? await this.dependencies.db.all<Row>('SELECT * FROM open_platform_applications WHERE group_id=? ORDER BY created_at DESC,id', [requireGroup(context)])
        : await this.dependencies.db.all<Row>('SELECT a.* FROM open_platform_applications a JOIN application_collaborators c ON c.application_id=a.id WHERE c.user_id=? ORDER BY a.created_at DESC,a.id', [context.actorId]);
    return rows.map(mapApplication);
  }

  async getApplication(context: AccessContext, applicationId: string): Promise<Record<string, unknown>> {
    const access = await this.applicationAccess(context, applicationId);
    const [permissions, policies, collaborators, credentials, webhooks] = await Promise.all([
      this.dependencies.db.all<{ permission: string }>('SELECT permission FROM application_permission_grants WHERE application_id=? ORDER BY permission', [applicationId]),
      this.dependencies.db.get<Row>('SELECT * FROM application_policies WHERE application_id=?', [applicationId]),
      this.dependencies.db.all<Row>('SELECT c.id,c.user_id,u.username,u.display_name,c.role,c.created_at,c.updated_at FROM application_collaborators c JOIN users u ON u.id=c.user_id WHERE c.application_id=? ORDER BY c.role,c.created_at', [applicationId]),
      this.dependencies.db.all<Row>('SELECT id,kind,name,token_prefix,token_fingerprint,scopes_json,allowed_ip_cidrs_json,status,not_before,expires_at,revoked_at,last_used_at,last_source_hash,rotated_from_id,replaced_by_id,grace_ends_at,created_by,created_at FROM application_credentials WHERE application_id=? ORDER BY created_at DESC', [applicationId]),
      this.dependencies.db.all<Row>('SELECT id,url,secret_id,next_secret_id,next_activates_at,enabled,event_types_json,device_ids_json,attributes_json,filter_version,updated_at,created_at FROM event_endpoints WHERE application_id=? ORDER BY created_at DESC', [applicationId]),
    ]);
    return { ...mapApplication(access.application), collaborator_role: access.collaboratorRole, permissions: permissions.map((item) => item.permission), policies, collaborators, credentials: credentials.map((item) => ({ ...item, scopes: parseJsonArray(item.scopes_json), allowed_ip_cidrs: parseJsonArray(item.allowed_ip_cidrs_json), scopes_json: undefined, allowed_ip_cidrs_json: undefined })), webhooks: webhooks.map((item) => ({ id: item.id, url: item.url, secret_id: item.secret_id, next_secret_id: item.next_secret_id, next_activates_at: item.next_activates_at, enabled: Boolean(item.enabled), filter: { event_types: parseJsonArray(item.event_types_json), ...(parseJsonArray(item.device_ids_json).length ? { device_ids: parseJsonArray(item.device_ids_json) } : {}), ...(parseJsonArray(item.attributes_json).length ? { attributes: parseJsonArray(item.attributes_json).map(Number) } : {}) }, filter_version: Number(item.filter_version), updated_at: item.updated_at, created_at: item.created_at })) };
  }

  async capabilities(context: AccessContext): Promise<Record<string, unknown>> {
    if (!context.applicationId) throw new OpenPlatformError(403, 'APPLICATION_CREDENTIAL_REQUIRED', 'An Application credential is required');
    const application = await this.dependencies.db.get<Row>('SELECT id,group_id,name,environment,status,channels_json,version FROM open_platform_applications WHERE id=? AND status=\'active\'', [context.applicationId]);
    if (!application) throw new OpenPlatformError(401, 'APPLICATION_UNAVAILABLE', 'Application is unavailable');
    const policies = await this.dependencies.db.get<Row>('SELECT requests_per_minute,mcp_calls_per_minute,sync_commands_per_hour,download_grants_per_minute,download_grants_per_day,max_active_download_grants,download_ttl_seconds,max_result_items FROM application_policies WHERE application_id=?', [context.applicationId]);
    return { api_version: API_VERSION, application: { ...application, channels: parseJsonArray(application.channels_json), channels_json: undefined }, credential_id: context.credentialId ?? null, principal_id: context.principalId ?? context.actorId, channel: context.channel ?? 'rest', scopes: [...context.scopes].sort(), quotas: policies, features: { rest: true, mcp_stdio: true, mcp_remote: true, recording_delivery: 'external_temporary_url', download_delivery_mode: this.dependencies.config.downloadDeliveryMode, object_store_range: this.dependencies.config.storageDriver === 's3_direct', recording_bytes_in_api: false } };
  }

  async listDevices(context: AccessContext): Promise<Device[]> {
    requireScope(context, 'devices:read'); const guard = sqlGroupGuard(context);
    return (await this.dependencies.db.all<Row>(`SELECT d.* FROM devices d WHERE d.deleted_at IS NULL AND d.claim_status='active' AND ${guard.clause} ORDER BY d.created_at DESC,d.id`, guard.params)).map(mapDevice);
  }

  async getDevice(context: AccessContext, deviceId: string): Promise<Device> {
    requireScope(context, 'devices:read'); const guard = sqlGroupGuard(context); const row = await this.dependencies.db.get<Row>(`SELECT d.* FROM devices d WHERE d.id=? AND d.deleted_at IS NULL AND d.claim_status='active' AND ${guard.clause}`, [deviceId, ...guard.params]); if (!row) throw new AccessDeniedError(); return mapDevice(row);
  }

  async getDeviceCapabilities(context: AccessContext, deviceId: string) {
    requireScope(context, 'devices:read');
    const guard = sqlGroupGuard(context);
    const row = await this.dependencies.db.get<Row>(`SELECT d.* FROM devices d WHERE d.id=? AND d.deleted_at IS NULL AND d.claim_status='active' AND ${guard.clause}`, [deviceId, ...guard.params]);
    if (!row) throw new AccessDeniedError();
    return deviceCapabilities(row);
  }

  async syncDevice(context: AccessContext, deviceId: string, idempotencyKey: string): Promise<Record<string, unknown>> {
    requireScope(context, 'devices:sync'); if (!idempotencyKey) throw new OpenPlatformError(400, 'IDEMPOTENCY_KEY_REQUIRED', 'Idempotency-Key is required'); await this.getDevice({ ...context, scopes: new Set([...context.scopes, 'devices:read']) }, deviceId);
    const commandId = id('cmd'); const scope = context.applicationId ? `application:${context.applicationId}:open-platform` : `${context.actorType}:${context.actorId}:open-platform`; const hash = requestHash({ deviceId, kind: 'sync' });
    const timestamp = now();
    const sameRequest = await this.dependencies.db.get<Row>('SELECT * FROM commands WHERE caller_scope=? AND kind=? AND idempotency_key=?', [scope, 'sync', idempotencyKey]);
    if (sameRequest) { if (sameRequest.request_hash !== hash) throw new OpenPlatformError(409, 'IDEMPOTENCY_CONFLICT', 'Idempotency key was used with another request'); return mapPublicCommand(sameRequest); }
    // A device has one file-command lane. Coalesce callers onto the existing
    // live scan instead of creating commands that can only run sequentially
    // and repeatedly rediscover the same inventory.
    const active = await this.dependencies.db.get<Row>("SELECT * FROM commands WHERE device_id=? AND kind='sync' AND status IN ('queued','dispatched','running') AND deadline_at>? ORDER BY created_at,id LIMIT 1", [deviceId, timestamp]);
    if (active) return mapPublicCommand(active);
    const statements: SqlStatement[] = [{ sql: 'INSERT INTO commands(id,device_id,kind,status,idempotency_key,caller_scope,request_hash,deadline_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)', params: [commandId, deviceId, 'sync', 'queued', idempotencyKey, scope, hash, plus(15 * 60_000), timestamp, timestamp] }];
    if (context.applicationId) { const bucketStart = new Date(Math.floor(Date.now() / 3_600_000) * 3_600_000).toISOString(); statements.push({ sql: `INSERT INTO application_usage_buckets(application_id,channel,bucket_start,sync_command_count) VALUES(?,?,?,1)
      ON CONFLICT(application_id,channel,bucket_start) DO UPDATE SET sync_command_count=application_usage_buckets.sync_command_count+1
      WHERE application_usage_buckets.sync_command_count<(SELECT sync_commands_per_hour FROM application_policies WHERE application_id=?)`, params: [context.applicationId, 'quota_sync', bucketStart, context.applicationId], expectChanges: 1 }); }
    try { await this.dependencies.db.batch(statements); }
    catch (error) { const existing = await this.dependencies.db.get<Row>('SELECT * FROM commands WHERE caller_scope=? AND kind=? AND idempotency_key=?', [scope, 'sync', idempotencyKey]); if (existing) { if (existing.request_hash !== hash) throw new OpenPlatformError(409, 'IDEMPOTENCY_CONFLICT', 'Idempotency key was used with another request'); return mapPublicCommand(existing); } if (error instanceof Error && error.message.startsWith('DATABASE_CAS_FAILED')) throw new OpenPlatformError(429, 'SYNC_COMMAND_RATE_LIMITED', 'Application synchronization quota exceeded'); throw error; }
    await this.dependencies.gateway.dispatchSync(deviceId, commandId); const created = await this.dependencies.db.get<Row>('SELECT * FROM commands WHERE id=?', [commandId]); return mapPublicCommand(created!);
  }

  async getCommand(context: AccessContext, commandId: string): Promise<Row> {
    requireScope(context, 'commands:read'); const guard = sqlGroupGuard(context); const row = await this.dependencies.db.get<Row>(`SELECT c.* FROM commands c JOIN devices d ON d.id=c.device_id WHERE c.id=? AND d.deleted_at IS NULL AND d.claim_status='active' AND ${guard.clause}`, [commandId, ...guard.params]); if (!row) throw new AccessDeniedError(); return mapPublicCommand(row);
  }

  async listDeviceCommands(context: AccessContext, deviceId: string): Promise<Record<string, unknown>> {
    requireScope(context, 'commands:read');
    const guard = sqlGroupGuard(context);
    const device = await this.dependencies.db.get<Row>(`SELECT d.id FROM devices d WHERE d.id=? AND d.deleted_at IS NULL AND d.claim_status='active' AND ${guard.clause}`, [deviceId, ...guard.params]);
    if (!device) throw new AccessDeniedError();
    const rows = await this.dependencies.db.all<Row>(`SELECT c.*,
      (SELECT e.id FROM events e WHERE e.device_id=c.device_id AND e.type IN ('command.succeeded','command.failed','command.expired') AND e.payload_json LIKE '%' || c.id || '%' ORDER BY e.created_at DESC,e.id DESC LIMIT 1) AS terminal_event_id
      FROM commands c WHERE c.device_id=? ORDER BY c.created_at DESC,c.id DESC LIMIT 50`, [deviceId]);
    return { items: rows.map((row) => {
      const command = mapPublicCommand(row);
      const durationMs = command.completed_at ? Math.max(0, Date.parse(command.completed_at) - Date.parse(command.requested_at)) : null;
      return { ...command, duration_ms: Number.isFinite(durationMs) ? durationMs : null, terminal_event_id: row.terminal_event_id ?? null };
    }) };
  }

  async listRecordings(context: AccessContext, query: Row): Promise<Record<string, unknown>> {
    requireScope(context, 'recordings:read'); const guard = sqlGroupGuard(context); const params: unknown[] = [...guard.params]; let where = `${guard.clause} AND f.deletion_status='active'`;
    if (query.status) { where += ' AND f.status=?'; params.push(String(query.status)); }
    if (query.device_id) { where += ' AND f.device_id=?'; params.push(String(query.device_id)); }
    if (query.attribute !== undefined) { const attribute = Number(query.attribute); if (!Number.isSafeInteger(attribute) || attribute < 0 || attribute > 2) throw new OpenPlatformError(400, 'INVALID_ATTRIBUTE', 'attribute is invalid'); where += ' AND f.attribute=?'; params.push(attribute); }
    if (query.from) { where += ' AND f.created_at>=?'; params.push(String(query.from)); }
    if (query.to) { where += ' AND f.created_at<=?'; params.push(String(query.to)); }
    if (query.search) { const search = String(query.search).trim(); if (search.length > 128) throw new OpenPlatformError(400, 'INVALID_SEARCH', 'search is too long'); where += " AND (d.sn LIKE ? ESCAPE '\\' OR CAST(f.session_id AS TEXT)=?)"; params.push(`%${search.replaceAll('\\', '\\\\').replaceAll('%', '\\%').replaceAll('_', '\\_')}%`, search); }
    const resultPolicy = context.applicationId ? await this.dependencies.db.get<{ max_result_items: number }>('SELECT max_result_items FROM application_policies WHERE application_id=?', [context.applicationId]) : null; const maximum = Math.min(Number(resultPolicy?.max_result_items ?? 100), 100); const limit = Math.min(Number(query.limit ?? maximum), maximum); if (!Number.isSafeInteger(limit) || limit < 1) throw new OpenPlatformError(400, 'INVALID_LIMIT', 'limit is invalid');
    const cursor = cursorDecode(query.cursor); if (cursor) { where += ' AND (f.created_at<? OR (f.created_at=? AND f.id<?))'; params.push(cursor.createdAt, cursor.createdAt, cursor.itemId); }
    const rows = await this.dependencies.db.all<Row>(`SELECT f.* FROM recording_files f JOIN devices d ON d.id=f.device_id WHERE ${where} ORDER BY f.created_at DESC,f.id DESC LIMIT ?`, [...params, limit + 1]);
    const items = rows.slice(0, limit); const last = items.at(-1); return { items: items.map(mapRecording), count: items.length, next_cursor: rows.length > limit && last ? cursorEncode(String(last.created_at), String(last.id)) : null };
  }

  async getRecording(context: AccessContext, recordingId: string): Promise<RecordingFile> {
    requireScope(context, 'recordings:read'); const guard = sqlGroupGuard(context); const row = await this.dependencies.db.get<Row>(`SELECT f.* FROM recording_files f JOIN devices d ON d.id=f.device_id WHERE f.id=? AND f.deletion_status='active' AND ${guard.clause}`, [recordingId, ...guard.params]); if (!row) throw new AccessDeniedError(); return mapRecording(row);
  }

  private deriveDownloadToken(grantId: string, keyVersion: number): string {
    const key = this.dependencies.config.masterKeys.get(keyVersion); if (!key) throw new OpenPlatformError(503, 'DOWNLOAD_KEY_UNAVAILABLE', 'Download signing key is unavailable');
    return createHmac('sha256', key).update('voicecan-recording-download-v1\0').update(grantId).digest('base64url');
  }

  async createDownloadLink(context: AccessContext, recordingId: string, input: { ttlSeconds?: number; purpose?: string; idempotencyKey: string }): Promise<RecordingDownloadLink> {
    requireScope(context, 'recordings:download_link:create');
    if (!context.applicationId || !['application_token', 'oauth'].includes(context.actorType)) throw new OpenPlatformError(403, 'APPLICATION_CREDENTIAL_REQUIRED', 'An Application credential is required');
    if (!input.idempotencyKey || input.idempotencyKey.length > 200) throw new OpenPlatformError(400, 'IDEMPOTENCY_KEY_REQUIRED', 'Idempotency-Key is required');
    if (input.purpose && input.purpose !== 'download') throw new OpenPlatformError(400, 'INVALID_DOWNLOAD_PURPOSE', 'Only download is supported');
    const policies = await this.dependencies.db.get<Row>('SELECT * FROM application_policies WHERE application_id=?', [context.applicationId]); if (!policies) throw new OpenPlatformError(409, 'APPLICATION_POLICY_MISSING', 'Application policy is missing');
    const configuredTtl = Number(policies.download_ttl_seconds); const ttlSeconds = input.ttlSeconds ?? configuredTtl;
    const minimum = this.dependencies.config.downloadGrantMinTtlSeconds; const maximum = Math.min(this.dependencies.config.downloadGrantMaxTtlSeconds, configuredTtl);
    if (!Number.isSafeInteger(ttlSeconds) || ttlSeconds < minimum || ttlSeconds > maximum) throw new OpenPlatformError(400, 'INVALID_DOWNLOAD_TTL', `ttl_seconds must be between ${minimum} and ${maximum}`);
    const existing = await this.dependencies.db.get<Row>('SELECT g.id AS grant_id,g.expires_at,g.purpose,g.key_version,g.request_hash,g.file_id,f.* FROM recording_download_grants g JOIN recording_files f ON f.id=g.file_id WHERE g.application_id=? AND g.idempotency_key=?', [context.applicationId, input.idempotencyKey]);
    const hash = requestHash({ recordingId, ttlSeconds, purpose: 'download' });
    if (existing) {
      if (existing.request_hash !== hash) throw new OpenPlatformError(409, 'IDEMPOTENCY_CONFLICT', 'Idempotency key was used with another request');
      return this.downloadLinkResult(existing, this.deriveDownloadToken(String(existing.grant_id), Number(existing.key_version)));
    }
    const guard = sqlGroupGuard(context); const file = await this.dependencies.db.get<Row>(`SELECT f.*,d.group_id,d.ownership_epoch FROM recording_files f JOIN devices d ON d.id=f.device_id WHERE f.id=? AND f.status='synced' AND f.deletion_status='active' AND f.storage_locator IS NOT NULL AND ${guard.clause}`, [recordingId, ...guard.params]); if (!file) throw new AccessDeniedError();
    const deliveryMode = String(policies.download_delivery_mode); if (deliveryMode === 'external_object_only' && !String(file.storage_locator).startsWith('s3:')) throw new OpenPlatformError(409, 'EXTERNAL_STORAGE_REQUIRED', 'This application only permits external object delivery');
    const active = await this.dependencies.db.get<{ count: number }>('SELECT COUNT(*) AS count FROM recording_download_grants WHERE application_id=? AND revoked_at IS NULL AND expires_at>? AND request_count<max_requests', [context.applicationId, now()]);
    if (Number(active?.count ?? 0) >= Number(policies.max_active_download_grants)) throw new OpenPlatformError(429, 'DOWNLOAD_GRANT_LIMIT', 'Too many active download grants');
    const minute = new Date(Date.now() - 60_000).toISOString(); const day = new Date(Date.now() - 24 * 60 * 60_000).toISOString();
    const [minuteCount, dayCount] = await Promise.all([
      this.dependencies.db.get<{ count: number }>('SELECT COUNT(*) AS count FROM recording_download_grants WHERE application_id=? AND created_at>=?', [context.applicationId, minute]),
      this.dependencies.db.get<{ count: number }>('SELECT COUNT(*) AS count FROM recording_download_grants WHERE application_id=? AND created_at>=?', [context.applicationId, day]),
    ]);
    if (Number(minuteCount?.count ?? 0) >= Number(policies.download_grants_per_minute) || Number(dayCount?.count ?? 0) >= Number(policies.download_grants_per_day)) throw new OpenPlatformError(429, 'DOWNLOAD_GRANT_RATE_LIMITED', 'Download grant rate limit exceeded');
    const grantId = id('download_grant'); const keyVersion = this.dependencies.config.masterKeyVersion; const rawToken = this.deriveDownloadToken(grantId, keyVersion); const expiresAt = plus(ttlSeconds * 1_000); const createdAt = now();
    await this.dependencies.db.run('INSERT INTO recording_download_grants(id,token_hash,file_id,device_id,group_id,ownership_epoch,application_id,credential_id,oauth_token_id,key_version,purpose,expires_at,max_requests,idempotency_key,request_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [grantId, tokenHash(rawToken, this.dependencies.config.groupTokenPepper), recordingId, file.device_id, file.group_id, file.ownership_epoch, context.applicationId, context.credentialId ?? null, context.actorType === 'oauth' ? context.actorId : null, keyVersion, 'download', expiresAt, 1, input.idempotencyKey, hash, createdAt]);
    const bucketStart = new Date(Math.floor(Date.now() / 60_000) * 60_000).toISOString(); await this.dependencies.db.run('INSERT INTO application_usage_buckets(application_id,channel,bucket_start,download_grant_count) VALUES(?,?,?,1) ON CONFLICT(application_id,channel,bucket_start) DO UPDATE SET download_grant_count=application_usage_buckets.download_grant_count+1', [context.applicationId, context.channel ?? 'rest', bucketStart]);
    return this.downloadLinkResult({ ...file, grant_id: grantId, file_id: recordingId, expires_at: expiresAt, purpose: 'download' }, rawToken);
  }

  private downloadLinkResult(row: Row, rawToken: string): RecordingDownloadLink {
    const recording = { ...row, id: row.file_id ?? row.id };
    return { grant_id: String(row.grant_id ?? row.id), download_url: `${this.dependencies.config.publicBaseUrl}/recording-download/v1/${rawToken}`, expires_at: String(row.expires_at), purpose: 'download', content_length: Number(row.actual_size), content_type: String(row.media_content_type ?? 'application/octet-stream'), filename: recordingFilename(recording), sha256: row.sha256 === null ? null : String(row.sha256), range_supported: String(row.storage_locator ?? '').startsWith('s3:'), delivery: 'external_temporary_url' };
  }

  async revokeDownloadLink(context: AccessContext, grantId: string): Promise<{ grant_id: string; revoked: true }> {
    requireScope(context, 'recordings:download_link:revoke'); if (!context.applicationId) throw new OpenPlatformError(403, 'APPLICATION_CREDENTIAL_REQUIRED', 'An Application credential is required');
    const result = await this.dependencies.db.run('UPDATE recording_download_grants SET revoked_at=COALESCE(revoked_at,?) WHERE id=? AND application_id=?', [now(), grantId, context.applicationId]); if (result.changes !== 1) throw new AccessDeniedError(); return { grant_id: grantId, revoked: true };
  }

  async getDownloadGrant(context: AccessContext, grantId: string): Promise<Record<string, unknown>> {
    requireScope(context, 'recordings:download_link:revoke');
    if (!context.applicationId) throw new OpenPlatformError(403, 'APPLICATION_CREDENTIAL_REQUIRED', 'An Application credential is required');
    const row = await this.dependencies.db.get<Row>('SELECT id,file_id,device_id,expires_at,max_requests,request_count,first_used_at,last_used_at,revoked_at,created_at FROM recording_download_grants WHERE id=? AND application_id=?', [grantId, context.applicationId]);
    if (!row) throw new AccessDeniedError();
    return { grant_id: row.id, recording_id: row.file_id, device_id: row.device_id, expires_at: row.expires_at, consumed: Number(row.request_count) > 0, first_used_at: row.first_used_at, last_used_at: row.last_used_at, revoked_at: row.revoked_at, created_at: row.created_at };
  }

  async listEvents(context: AccessContext, query: Row): Promise<Record<string, unknown>> {
    requireScope(context, 'events:read'); const guard = sqlGroupGuard(context); const params: unknown[] = [...guard.params]; let where = guard.clause; if (query.event_type) { where += ' AND e.type=?'; params.push(String(query.event_type)); } if (query.device_id) { where += ' AND e.device_id=?'; params.push(String(query.device_id)); } if (query.from) { where += ' AND e.created_at>=?'; params.push(String(query.from)); } if (query.to) { where += ' AND e.created_at<=?'; params.push(String(query.to)); }
    const total = await this.dependencies.db.get<{ count: number }>(`SELECT COUNT(*) AS count FROM events e JOIN devices d ON d.id=e.device_id WHERE e.owner_group_id=d.group_id AND e.ownership_epoch=d.ownership_epoch AND ${where}`, params);
    const cursor = cursorDecode(query.cursor); if (cursor) { where += ' AND (e.created_at<? OR (e.created_at=? AND e.id<?))'; params.push(cursor.createdAt, cursor.createdAt, cursor.itemId); }
    const resultPolicy = context.applicationId ? await this.dependencies.db.get<{ max_result_items: number }>('SELECT max_result_items FROM application_policies WHERE application_id=?', [context.applicationId]) : null; const maximum = Math.min(Number(resultPolicy?.max_result_items ?? 100), 100); const limit = Math.min(Number(query.limit ?? maximum), maximum); if (!Number.isSafeInteger(limit) || limit < 1) throw new OpenPlatformError(400, 'INVALID_LIMIT', 'limit is invalid');
    const rows = await this.dependencies.db.all<Row>(`SELECT e.* FROM events e JOIN devices d ON d.id=e.device_id WHERE e.owner_group_id=d.group_id AND e.ownership_epoch=d.ownership_epoch AND ${where} ORDER BY e.created_at DESC,e.id DESC LIMIT ?`, [...params, limit + 1]); const items = rows.slice(0, limit); const last = items.at(-1);
    return { items: items.map((row) => ({ id: row.id, type: row.type, api_version: API_VERSION, created_at: row.created_at, data: JSON.parse(String(row.payload_json)) })), count: items.length, total_count: Number(total?.count ?? 0), next_cursor: rows.length > limit && last ? cursorEncode(String(last.created_at), String(last.id)) : null };
  }

  async consumeDownload(request: FastifyRequest, reply: FastifyReply, rawToken: string): Promise<FastifyReply> {
    const token = tokenHash(rawToken, this.dependencies.config.groupTokenPepper); const grant = await this.dependencies.db.get<Row>(`SELECT g.*,f.storage_locator,f.actual_size,f.sha256,f.media_content_type,f.media_filename_extension,f.status AS file_status,f.deletion_status,f.legal_hold,d.group_id AS current_group_id,d.ownership_epoch AS current_ownership_epoch,a.status AS application_status,c.status AS credential_status,c.revoked_at AS credential_revoked,o.revoked_at AS oauth_revoked,o.expires_at AS oauth_expires_at
      FROM recording_download_grants g JOIN recording_files f ON f.id=g.file_id JOIN devices d ON d.id=g.device_id JOIN open_platform_applications a ON a.id=g.application_id LEFT JOIN application_credentials c ON c.id=g.credential_id LEFT JOIN oauth_access_tokens o ON o.id=g.oauth_token_id WHERE g.token_hash=?`, [token]);
    const valid = grant && !grant.revoked_at && String(grant.expires_at) > now() && Number(grant.request_count) < Number(grant.max_requests)
      && grant.file_status === 'synced' && grant.deletion_status === 'active' && !Boolean(grant.legal_hold) && grant.application_status === 'active'
      && grant.group_id === grant.current_group_id && Number(grant.ownership_epoch) === Number(grant.current_ownership_epoch)
      && (!grant.credential_id || (grant.credential_status === 'active' && !grant.credential_revoked))
      && (!grant.oauth_token_id || (!grant.oauth_revoked && String(grant.oauth_expires_at) > now()));
    if (!valid || !grant?.storage_locator) throw new OpenPlatformError(404, 'DOWNLOAD_GRANT_INVALID', 'Download grant is invalid');
    if (request.headers.range) throw new OpenPlatformError(416, 'RANGE_NOT_SUPPORTED', 'Download grants do not support byte ranges');
    const usedAt = now(); const changed = await this.dependencies.db.run('UPDATE recording_download_grants SET request_count=request_count+1,first_used_at=COALESCE(first_used_at,?),last_used_at=? WHERE id=? AND revoked_at IS NULL AND expires_at>? AND request_count<max_requests', [usedAt, usedAt, grant.id, usedAt]); if (changed.changes !== 1) throw new OpenPlatformError(404, 'DOWNLOAD_GRANT_INVALID', 'Download grant is invalid');
    const bucketStart = new Date(Math.floor(Date.now() / 60_000) * 60_000).toISOString(); await this.dependencies.db.run('INSERT INTO application_usage_buckets(application_id,channel,bucket_start,download_consume_count) VALUES(?,?,?,1) ON CONFLICT(application_id,channel,bucket_start) DO UPDATE SET download_consume_count=application_usage_buckets.download_consume_count+1', [grant.application_id, 'download', bucketStart]);
    await this.dependencies.db.run('INSERT INTO audit_logs(id,actor_id,action,resource_type,resource_id,group_id,application_id,credential_id,principal_id,request_id,result,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)', [id('audit'), String(grant.application_id), 'recording.download_grant_consumed', 'recording_download_grant', grant.id, grant.group_id, grant.application_id, grant.credential_id ?? null, grant.oauth_token_id ?? null, request.id, 'success', usedAt]);
    reply.header('cache-control', 'private, no-store').header('referrer-policy', 'no-referrer').header('content-disposition', `attachment; filename="${recordingFilename({ ...grant, id: grant.file_id })}"`).header('x-content-type-options', 'nosniff');
    if (String(grant.storage_locator).startsWith('s3:')) {
      if (!this.dependencies.s3Storage) throw new OpenPlatformError(503, 'STORAGE_UNAVAILABLE', 'Storage driver is unavailable');
      const policy = await this.dependencies.db.get<{ s3_redirect_ttl_seconds: number }>('SELECT s3_redirect_ttl_seconds FROM application_policies WHERE application_id=?', [grant.application_id]); const remaining = Math.max(1, Math.floor((Date.parse(String(grant.expires_at)) - Date.now()) / 1_000)); const ttl = Math.min(Number(policy?.s3_redirect_ttl_seconds ?? this.dependencies.config.s3DownloadRedirectTtlSeconds), this.dependencies.config.s3DownloadRedirectTtlSeconds, remaining);
      return reply.code(303).header('location', await this.dependencies.s3Storage.presignDownload(String(grant.storage_locator), ttl)).send();
    }
    const policy = await this.dependencies.db.get<{ download_delivery_mode: string }>('SELECT download_delivery_mode FROM application_policies WHERE application_id=?', [grant.application_id]); if (policy?.download_delivery_mode === 'external_object_only' || this.dependencies.config.downloadDeliveryMode === 'external_object_only') throw new OpenPlatformError(409, 'EXTERNAL_STORAGE_REQUIRED', 'External object delivery is required');
    reply.header('content-length', String(grant.actual_size)).header('content-type', String(grant.media_content_type ?? 'application/octet-stream')); if (grant.sha256) reply.header('etag', `"sha256-${grant.sha256}"`); return reply.send(createReadStream(this.dependencies.storage.resolveLocator(String(grant.storage_locator))));
  }
}

export function registerOpenPlatformRoutes(dependencies: OpenPlatformDependencies): OpenPlatformService {
  const { app, db, config, resolveAccess, audit } = dependencies;
  const service = new OpenPlatformService(dependencies);

  app.get('/api/v1/open-platform/permission-catalog', async (request, reply) => { const context = await resolveAccess(request); if (context.actorType !== 'user') throw new AccessDeniedError(); return success(reply, { permissions: OPEN_PLATFORM_PERMISSIONS, templates: OPEN_PLATFORM_PERMISSION_TEMPLATES }); });
  app.get('/api/v1/open-platform/overview', async (request, reply) => {
    const context = await resolveAccess(request); if (context.actorType !== 'user' || (!context.isSystemAdmin && !context.isGroupAdmin)) throw new AccessDeniedError(); const params: unknown[] = []; const filter = context.isSystemAdmin ? '1=1' : 'group_id=?'; if (!context.isSystemAdmin) params.push(requireGroup(context)); const applications = await db.get<Row>(`SELECT COUNT(*) AS total,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) AS active,SUM(CASE WHEN status='suspended' THEN 1 ELSE 0 END) AS suspended FROM open_platform_applications WHERE ${filter}`, params); const credentialParams = [...params]; const credentials = await db.get<Row>(`SELECT COUNT(*) AS total,SUM(CASE WHEN c.status='active' AND c.expires_at>? THEN 1 ELSE 0 END) AS active,SUM(CASE WHEN c.status='active' AND c.expires_at<=? THEN 1 ELSE 0 END) AS expiring_7d,SUM(CASE WHEN c.last_used_at IS NULL OR c.last_used_at<? THEN 1 ELSE 0 END) AS unused_30d FROM application_credentials c JOIN open_platform_applications a ON a.id=c.application_id WHERE ${context.isSystemAdmin ? '1=1' : 'a.group_id=?'}`, [now(), plus(7 * 24 * 60 * 60_000), new Date(Date.now() - 30 * 24 * 60 * 60_000).toISOString(), ...credentialParams]); const since = new Date(Date.now() - 24 * 60 * 60_000).toISOString(); const calls = await db.get<Row>(`SELECT COUNT(*) AS requests,SUM(CASE WHEN l.status_code>=400 THEN 1 ELSE 0 END) AS errors,SUM(CASE WHEN l.status_code=429 THEN 1 ELSE 0 END) AS rate_limited FROM open_platform_api_logs l JOIN open_platform_applications a ON a.id=l.application_id WHERE l.created_at>=?${context.isSystemAdmin ? '' : ' AND a.group_id=?'}`, [since, ...params]); const downloads = await db.get<Row>(`SELECT COUNT(*) AS created,SUM(CASE WHEN g.first_used_at IS NOT NULL THEN 1 ELSE 0 END) AS consumed,SUM(CASE WHEN g.revoked_at IS NULL AND g.expires_at>? AND g.request_count<g.max_requests THEN 1 ELSE 0 END) AS active FROM recording_download_grants g WHERE g.created_at>=?${context.isSystemAdmin ? '' : ' AND g.group_id=?'}`, [now(), since, ...params]); const alerts = await db.get<Row>(`SELECT COUNT(*) AS open,SUM(CASE WHEN severity='critical' THEN 1 ELSE 0 END) AS critical FROM open_platform_security_alerts s WHERE s.status='open'${context.isSystemAdmin ? '' : ' AND s.application_id IN (SELECT id FROM open_platform_applications WHERE group_id=?)'}`, params); return success(reply, { applications, credentials, calls_24h: calls, downloads_24h: downloads, security_alerts: alerts });
  });
  app.get('/api/v1/open-platform/applications', async (request, reply) => success(reply, await service.listApplications(await resolveAccess(request))));
  app.post('/api/v1/open-platform/applications', async (request, reply) => {
    const context = await resolveAccess(request, true); const body = bodyOf(request); const groupId = context.isSystemAdmin ? requiredString(body, 'group_id', 100) : requireGroup(context); requireGroupAdmin(context, groupId);
    const name = requiredString(body, 'name', 120); const description = optionalString(body, 'description', 2000); const environment = optionalString(body, 'environment', 32) ?? 'development'; if (!['development', 'staging', 'production'].includes(environment)) throw new OpenPlatformError(400, 'INVALID_ENVIRONMENT', 'environment is invalid');
    const channels = validChannels(body.channels === undefined ? ['rest'] : stringArray(body, 'channels')); const permissions = validPermissions(body.permissions === undefined ? [...OPEN_PLATFORM_PERMISSION_TEMPLATES.metadata_reader] : stringArray(body, 'permissions')); const applicationId = id('app'); const timestamp = now();
    await db.batch([
      { sql: 'INSERT INTO open_platform_applications(id,group_id,name,description,environment,status,channels_json,owner_user_id,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)', params: [applicationId, groupId, name, description, environment, 'active', JSON.stringify(channels), context.actorId, context.actorId, timestamp, timestamp] },
      { sql: 'INSERT INTO application_collaborators(id,application_id,user_id,role,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?)', params: [id('collab'), applicationId, context.actorId, 'owner', context.actorId, timestamp, timestamp] },
      { sql: 'INSERT INTO application_policies(application_id,download_ttl_seconds,s3_redirect_ttl_seconds,download_delivery_mode,updated_by,updated_at) VALUES(?,?,?,?,?,?)', params: [applicationId, config.downloadGrantDefaultTtlSeconds, config.s3DownloadRedirectTtlSeconds, environment === 'production' ? 'external_object_only' : config.downloadDeliveryMode, context.actorId, timestamp] },
      ...permissions.map((permission): SqlStatement => ({ sql: 'INSERT INTO application_permission_grants(application_id,permission,created_by,created_at) VALUES(?,?,?,?)', params: [applicationId, permission, context.actorId, timestamp] })),
    ]);
    await audit(request, context, 'open_platform.application_created', 'open_platform_application', applicationId, groupId, optionalString(body, 'reason', 256) ?? undefined); return success(reply, await service.getApplication(context, applicationId), 201);
  });
  app.get('/api/v1/open-platform/applications/:id', async (request, reply) => success(reply, await service.getApplication(await resolveAccess(request), String((request.params as Row).id))));
  app.patch('/api/v1/open-platform/applications/:id', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); const expectedVersion = integer(body, 'version', -1, 1, Number.MAX_SAFE_INTEGER); if (expectedVersion !== detail.version) throw new OpenPlatformError(409, 'RESOURCE_VERSION_CONFLICT', 'Application changed; reload before saving');
    const name = optionalString(body, 'name', 120) ?? String(detail.name); const description = body.description === undefined ? detail.description : optionalString(body, 'description', 2000); const status = optionalString(body, 'status', 32) ?? String(detail.status); if (!['active', 'suspended'].includes(status)) throw new OpenPlatformError(400, 'INVALID_STATUS', 'Use the archive operation to archive an Application'); const channels = body.channels === undefined ? detail.channels : validChannels(stringArray(body, 'channels'));
    const changed = await db.run('UPDATE open_platform_applications SET name=?,description=?,status=?,channels_json=?,version=version+1,updated_at=? WHERE id=? AND version=?', [name, description, status, JSON.stringify(channels), now(), applicationId, expectedVersion]); if (changed.changes !== 1) throw new OpenPlatformError(409, 'RESOURCE_VERSION_CONFLICT', 'Application changed; reload before saving');
    if (status !== 'active') await db.run("UPDATE application_credentials SET status='suspended' WHERE application_id=? AND status='active'", [applicationId]); if (status !== 'active' || !(channels as string[]).includes('webhook')) await db.run("UPDATE event_deliveries SET status='canceled',last_error='APPLICATION_CHANNEL_DISABLED',claimed_by=NULL,claim_expires_at=NULL WHERE endpoint_id IN (SELECT id FROM event_endpoints WHERE application_id=?) AND status='pending'", [applicationId]); await audit(request, context, `open_platform.application_${status === detail.status ? 'updated' : status}`, 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, await service.getApplication(context, applicationId));
  });
  app.delete('/api/v1/open-platform/applications/:id', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); const timestamp = now(); await db.batch([{ sql: "UPDATE open_platform_applications SET status='archived',version=version+1,updated_at=? WHERE id=? AND status<>'archived'", params: [timestamp, applicationId], expectChanges: 1 }, { sql: "UPDATE application_credentials SET status='revoked',revoked_at=COALESCE(revoked_at,?) WHERE application_id=? AND status<>'revoked'", params: [timestamp, applicationId] }, { sql: 'UPDATE recording_download_grants SET revoked_at=COALESCE(revoked_at,?) WHERE application_id=?', params: [timestamp, applicationId] }, { sql: "UPDATE oauth_access_tokens SET revoked_at=COALESCE(revoked_at,?) WHERE application_id=?", params: [timestamp, applicationId] }, { sql: 'UPDATE event_endpoints SET enabled=0 WHERE application_id=?', params: [applicationId] }, { sql: "UPDATE event_deliveries SET status='canceled',last_error='APPLICATION_ARCHIVED',claimed_by=NULL,claim_expires_at=NULL WHERE endpoint_id IN (SELECT id FROM event_endpoints WHERE application_id=?) AND status='pending'", params: [applicationId] }]); await audit(request, context, 'open_platform.application_archived', 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { id: applicationId, status: 'archived' });
  });
  app.get('/api/v1/open-platform/applications/:id/permissions', async (request, reply) => { const context = await resolveAccess(request); const detail = await service.getApplication(context, String((request.params as Row).id)); return success(reply, { application_id: detail.id, permissions: detail.permissions, catalog: OPEN_PLATFORM_PERMISSIONS }); });
  app.put('/api/v1/open-platform/applications/:id/permissions', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); if (integer(body, 'version', -1, 1, Number.MAX_SAFE_INTEGER) !== detail.version) throw new OpenPlatformError(409, 'RESOURCE_VERSION_CONFLICT', 'Application changed; reload before saving'); const permissions = validPermissions(stringArray(body, 'permissions')); const timestamp = now();
    await db.batch([{ sql: 'DELETE FROM application_permission_grants WHERE application_id=?', params: [applicationId] }, ...permissions.map((permission): SqlStatement => ({ sql: 'INSERT INTO application_permission_grants(application_id,permission,created_by,created_at) VALUES(?,?,?,?)', params: [applicationId, permission, context.actorId, timestamp] })), { sql: 'UPDATE open_platform_applications SET version=version+1,updated_at=? WHERE id=? AND version=?', params: [timestamp, applicationId, detail.version], expectChanges: 1 }]);
    const allowed = new Set(permissions); const credentials = await db.all<{ id: string; scopes_json: string }>('SELECT id,scopes_json FROM application_credentials WHERE application_id=? AND status IN (\'active\',\'suspended\')', [applicationId]); for (const credential of credentials) { const reduced = parseJsonArray(credential.scopes_json).filter((scope) => allowed.has(scope as OpenPlatformPermission)); await db.run('UPDATE application_credentials SET scopes_json=? WHERE id=?', [JSON.stringify(reduced), credential.id]); }
    if (!allowed.has('events:read')) await db.run("UPDATE event_deliveries SET status='canceled',last_error='EVENT_PERMISSION_REVOKED',claimed_by=NULL,claim_expires_at=NULL WHERE endpoint_id IN (SELECT id FROM event_endpoints WHERE application_id=?) AND status='pending'", [applicationId]);
    await audit(request, context, 'open_platform.permissions_updated', 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { application_id: applicationId, permissions, version: Number(detail.version) + 1 });
  });
  app.get('/api/v1/open-platform/applications/:id/collaborators', async (request, reply) => { const detail = await service.getApplication(await resolveAccess(request), String((request.params as Row).id)); return success(reply, detail.collaborators); });
  app.post('/api/v1/open-platform/applications/:id/collaborators', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); const userId = requiredString(body, 'user_id', 100); const role = requiredString(body, 'role', 32); if (!['developer', 'viewer'].includes(role)) throw new OpenPlatformError(400, 'INVALID_COLLABORATOR_ROLE', 'Use owner transfer to assign the owner role'); const eligible = await db.get('SELECT u.id FROM users u LEFT JOIN group_memberships gm ON gm.user_id=u.id AND gm.group_id=? AND gm.active=1 WHERE u.id=? AND u.disabled_at IS NULL AND (u.role=\'system_admin\' OR gm.id IS NOT NULL)', [detail.group_id, userId]); if (!eligible) throw new AccessDeniedError(); const timestamp = now();
    const existing = await db.get<{ id: string }>('SELECT id FROM application_collaborators WHERE application_id=? AND user_id=?', [applicationId, userId]); if (existing) await db.run('UPDATE application_collaborators SET role=?,updated_at=? WHERE id=?', [role, timestamp, existing.id]); else await db.run('INSERT INTO application_collaborators(id,application_id,user_id,role,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?)', [id('collab'), applicationId, userId, role, context.actorId, timestamp, timestamp]); await audit(request, context, 'open_platform.collaborator_updated', 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { application_id: applicationId, user_id: userId, role }, existing ? 200 : 201);
  });
  app.delete('/api/v1/open-platform/applications/:id/collaborators/:userId', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const applicationId = String(params.id); const userId = String(params.userId); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); if (userId === detail.owner_user_id) throw new OpenPlatformError(409, 'OWNER_CANNOT_BE_REMOVED', 'Transfer ownership before removing the owner'); const changed = await db.run('DELETE FROM application_collaborators WHERE application_id=? AND user_id=?', [applicationId, userId]); if (changed.changes !== 1) throw new AccessDeniedError(); await audit(request, context, 'open_platform.collaborator_removed', 'open_platform_application', applicationId, String(detail.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { application_id: applicationId, user_id: userId, removed: true }); });
  app.put('/api/v1/open-platform/applications/:id/owner', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); const userId = requiredString(body, 'user_id', 100); const eligible = await db.get('SELECT u.id FROM users u LEFT JOIN group_memberships gm ON gm.user_id=u.id AND gm.group_id=? AND gm.active=1 WHERE u.id=? AND u.disabled_at IS NULL AND (u.role=\'system_admin\' OR gm.id IS NOT NULL)', [detail.group_id, userId]); if (!eligible) throw new AccessDeniedError(); const timestamp = now(); const existing = await db.get<{ id: string }>('SELECT id FROM application_collaborators WHERE application_id=? AND user_id=?', [applicationId, userId]); const statements: SqlStatement[] = [{ sql: "UPDATE application_collaborators SET role='developer',updated_at=? WHERE application_id=? AND user_id=? AND role='owner'", params: [timestamp, applicationId, detail.owner_user_id] }, existing ? { sql: "UPDATE application_collaborators SET role='owner',updated_at=? WHERE id=?", params: [timestamp, existing.id] } : { sql: 'INSERT INTO application_collaborators(id,application_id,user_id,role,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?)', params: [id('collab'), applicationId, userId, 'owner', context.actorId, timestamp, timestamp] }, { sql: 'UPDATE open_platform_applications SET owner_user_id=?,version=version+1,updated_at=? WHERE id=? AND version=?', params: [userId, timestamp, applicationId, detail.version], expectChanges: 1 }]; await db.batch(statements); await audit(request, context, 'open_platform.owner_transferred', 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { application_id: applicationId, owner_user_id: userId, version: Number(detail.version) + 1 });
  });
  app.get('/api/v1/open-platform/applications/:id/policies', async (request, reply) => { const detail = await service.getApplication(await resolveAccess(request), String((request.params as Row).id)); return success(reply, detail.policies); });
  app.put('/api/v1/open-platform/applications/:id/policies', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'owner'); const detail = await service.getApplication(context, applicationId); const body = bodyOf(request); const current = detail.policies as Row; const policy = { requests_per_minute: integer(body, 'requests_per_minute', Number(current.requests_per_minute), 1, 10_000), mcp_calls_per_minute: integer(body, 'mcp_calls_per_minute', Number(current.mcp_calls_per_minute), 1, 1_000), sync_commands_per_hour: integer(body, 'sync_commands_per_hour', Number(current.sync_commands_per_hour), 1, 10_000), download_grants_per_minute: integer(body, 'download_grants_per_minute', Number(current.download_grants_per_minute), 1, 1_000), download_grants_per_day: integer(body, 'download_grants_per_day', Number(current.download_grants_per_day), 1, 100_000), max_active_download_grants: integer(body, 'max_active_download_grants', Number(current.max_active_download_grants), 1, 1_000), download_ttl_seconds: integer(body, 'download_ttl_seconds', Number(current.download_ttl_seconds), config.downloadGrantMinTtlSeconds, config.downloadGrantMaxTtlSeconds), s3_redirect_ttl_seconds: integer(body, 's3_redirect_ttl_seconds', Number(current.s3_redirect_ttl_seconds), 1, config.s3DownloadRedirectTtlSeconds), max_result_items: integer(body, 'max_result_items', Number(current.max_result_items), 1, 100) }; const mode = optionalString(body, 'download_delivery_mode', 32) ?? String(current.download_delivery_mode); if (!['gateway', 'external_object_only'].includes(mode)) throw new OpenPlatformError(400, 'INVALID_DOWNLOAD_DELIVERY_MODE', 'download_delivery_mode is invalid'); if ((detail.environment === 'production' || config.deploymentProfile === 'production') && mode !== 'external_object_only') throw new OpenPlatformError(409, 'EXTERNAL_STORAGE_REQUIRED', 'Production Applications require external_object_only recording delivery'); const cidrs = validCidrs(body.allowed_ip_cidrs === undefined ? parseJsonArray(current.allowed_ip_cidrs_json) : stringArray(body, 'allowed_ip_cidrs', 50));
    await db.run('UPDATE application_policies SET requests_per_minute=?,mcp_calls_per_minute=?,sync_commands_per_hour=?,download_grants_per_minute=?,download_grants_per_day=?,max_active_download_grants=?,download_ttl_seconds=?,s3_redirect_ttl_seconds=?,download_delivery_mode=?,max_result_items=?,allowed_ip_cidrs_json=?,updated_by=?,updated_at=? WHERE application_id=?', [policy.requests_per_minute, policy.mcp_calls_per_minute, policy.sync_commands_per_hour, policy.download_grants_per_minute, policy.download_grants_per_day, policy.max_active_download_grants, policy.download_ttl_seconds, policy.s3_redirect_ttl_seconds, mode, policy.max_result_items, JSON.stringify(cidrs), context.actorId, now(), applicationId]); await audit(request, context, 'open_platform.policies_updated', 'open_platform_application', applicationId, String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, await db.get<Row>('SELECT * FROM application_policies WHERE application_id=?', [applicationId]));
  });

  app.get('/api/v1/open-platform/applications/:id/credentials', async (request, reply) => { const detail = await service.getApplication(await resolveAccess(request), String((request.params as Row).id)); return success(reply, detail.credentials); });
  app.post('/api/v1/open-platform/applications/:id/credentials', async (request, reply) => {
    const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'developer'); const detail = await service.getApplication(context, applicationId); if (detail.status !== 'active') throw new OpenPlatformError(409, 'APPLICATION_NOT_ACTIVE', 'Activate the Application before creating a credential'); const body = bodyOf(request); const kind = optionalString(body, 'kind', 32) ?? 'api_token'; if (!['api_token', 'mcp_stdio_token'].includes(kind)) throw new OpenPlatformError(400, 'INVALID_CREDENTIAL_KIND', 'kind is invalid'); const requiredChannel = kind === 'mcp_stdio_token' ? 'mcp_stdio' : 'rest'; if (!(detail.channels as string[]).includes(requiredChannel)) throw new OpenPlatformError(409, 'APPLICATION_CHANNEL_DISABLED', `Enable the ${requiredChannel} channel before creating this credential`); const granted = new Set(detail.permissions as string[]); const scopes = validPermissions(body.scopes === undefined ? [...granted] : stringArray(body, 'scopes')); if (scopes.some((scope) => !granted.has(scope))) throw new OpenPlatformError(400, 'SCOPE_EXCEEDS_APPLICATION', 'Credential scope exceeds Application permissions'); const expiration = optionalString(body, 'expires_at', 64); if (detail.environment === 'production' && !expiration) throw new OpenPlatformError(400, 'EXPIRATION_REQUIRED', 'Production credentials require expires_at'); const expiresAt = expiration ?? plus(90 * 24 * 60 * 60_000); if (!Number.isFinite(Date.parse(expiresAt)) || Date.parse(expiresAt) <= Date.now() + 60_000 || Date.parse(expiresAt) > Date.now() + 365 * 24 * 60 * 60_000) throw new OpenPlatformError(400, 'INVALID_EXPIRATION', 'expires_at must be between one minute and one year from now'); const secret = `vcd_app_${opaqueToken()}`; const credentialId = id('credential'); const cidrs = validCidrs(body.allowed_ip_cidrs === undefined ? [] : stringArray(body, 'allowed_ip_cidrs', 50));
    await db.run('INSERT INTO application_credentials(id,application_id,group_id,kind,name,token_prefix,token_fingerprint,token_hash,scopes_json,allowed_ip_cidrs_json,status,expires_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [credentialId, applicationId, detail.group_id, kind, requiredString(body, 'name', 120), secret.slice(0, 16), fingerprint(secret), tokenHash(secret, config.groupTokenPepper), JSON.stringify(scopes), JSON.stringify(cidrs), 'active', expiresAt, context.actorId, now()]); await audit(request, context, 'open_platform.credential_created', 'application_credential', credentialId, String(detail.group_id), requiredString(body, 'reason', 256)); reply.header('cache-control', 'private, no-store'); return success(reply, { id: credentialId, application_id: applicationId, kind, name: body.name, token: secret, token_prefix: secret.slice(0, 16), token_fingerprint: fingerprint(secret), scopes, expires_at: expiresAt }, 201);
  });
  app.post('/api/v1/open-platform/applications/:id/credentials/:credentialId/rotate', async (request, reply) => {
    const context = await resolveAccess(request, true); const params = request.params as Row; const applicationId = String(params.id); const oldId = String(params.credentialId); await service.requireApplicationAccess(context, applicationId, 'developer'); const detail = await service.getApplication(context, applicationId); const old = await db.get<Row>('SELECT * FROM application_credentials WHERE id=? AND application_id=? AND status IN (\'active\',\'suspended\')', [oldId, applicationId]); if (!old) throw new AccessDeniedError(); const body = bodyOf(request); const graceSeconds = integer(body, 'grace_seconds', 0, 0, 86_400); const secret = `vcd_app_${opaqueToken()}`; const credentialId = id('credential'); const timestamp = now(); const graceEndsAt = graceSeconds === 0 ? timestamp : plus(graceSeconds * 1_000);
    await db.batch([{ sql: 'INSERT INTO application_credentials(id,application_id,group_id,kind,name,token_prefix,token_fingerprint,token_hash,scopes_json,allowed_ip_cidrs_json,status,expires_at,rotated_from_id,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', params: [credentialId, applicationId, old.group_id, old.kind, optionalString(body, 'name', 120) ?? `${old.name} (rotated)`, secret.slice(0, 16), fingerprint(secret), tokenHash(secret, config.groupTokenPepper), old.scopes_json, old.allowed_ip_cidrs_json, 'active', old.expires_at, oldId, context.actorId, timestamp] }, { sql: `UPDATE application_credentials SET replaced_by_id=?,grace_ends_at=?${graceSeconds === 0 ? ",status='revoked',revoked_at=?" : ''} WHERE id=?`, params: graceSeconds === 0 ? [credentialId, graceEndsAt, timestamp, oldId] : [credentialId, graceEndsAt, oldId], expectChanges: 1 }]); await audit(request, context, 'open_platform.credential_rotated', 'application_credential', oldId, String(detail.group_id), requiredString(body, 'reason', 256)); reply.header('cache-control', 'private, no-store'); return success(reply, { id: credentialId, token: secret, token_prefix: secret.slice(0, 16), token_fingerprint: fingerprint(secret), scopes: parseJsonArray(old.scopes_json), expires_at: old.expires_at, rotated_from_id: oldId, grace_ends_at: graceEndsAt }, 201);
  });
  app.post('/api/v1/open-platform/applications/:id/credentials/:credentialId/finish-rotation', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id), 'developer'); const detail = await service.getApplication(context, String(params.id)); const changed = await db.run("UPDATE application_credentials SET status='revoked',revoked_at=COALESCE(revoked_at,?),grace_ends_at=? WHERE id=? AND application_id=? AND replaced_by_id IS NOT NULL", [now(), now(), params.credentialId, params.id]); if (changed.changes !== 1) throw new AccessDeniedError(); await audit(request, context, 'open_platform.credential_rotation_finished', 'application_credential', String(params.credentialId), String(detail.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: params.credentialId, status: 'revoked' }); });
  app.post('/api/v1/open-platform/applications/:id/credentials/:credentialId/suspend', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id), 'developer'); const detail = await service.getApplication(context, String(params.id)); const body = bodyOf(request); const suspended = body.suspended !== false; const changed = await db.run('UPDATE application_credentials SET status=? WHERE id=? AND application_id=? AND status IN (\'active\',\'suspended\')', [suspended ? 'suspended' : 'active', params.credentialId, params.id]); if (changed.changes !== 1) throw new AccessDeniedError(); await audit(request, context, suspended ? 'open_platform.credential_suspended' : 'open_platform.credential_resumed', 'application_credential', String(params.credentialId), String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { id: params.credentialId, status: suspended ? 'suspended' : 'active' }); });
  app.post('/api/v1/open-platform/applications/:id/credentials/:credentialId/mark-leaked', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id), 'developer'); const detail = await service.getApplication(context, String(params.id)); const body = bodyOf(request); const timestamp = now(); const changed = await db.run("UPDATE application_credentials SET status='leaked',revoked_at=? WHERE id=? AND application_id=? AND status<>'revoked'", [timestamp, params.credentialId, params.id]); if (changed.changes !== 1) throw new AccessDeniedError(); await db.batch([{ sql: 'UPDATE recording_download_grants SET revoked_at=COALESCE(revoked_at,?) WHERE credential_id=?', params: [timestamp, params.credentialId] }, { sql: 'INSERT INTO open_platform_security_alerts(id,application_id,credential_id,severity,code,details_json,created_at) VALUES(?,?,?,?,?,?,?)', params: [id('alert'), params.id, params.credentialId, 'critical', 'CREDENTIAL_LEAKED', JSON.stringify({ reason: requiredString(body, 'reason', 256) }), timestamp] }]); await audit(request, context, 'open_platform.credential_marked_leaked', 'application_credential', String(params.credentialId), String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { id: params.credentialId, status: 'leaked' }); });
  app.delete('/api/v1/open-platform/applications/:id/credentials/:credentialId', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id), 'developer'); const detail = await service.getApplication(context, String(params.id)); const timestamp = now(); const changed = await db.run("UPDATE application_credentials SET status='revoked',revoked_at=COALESCE(revoked_at,?) WHERE id=? AND application_id=? AND status<>'revoked'", [timestamp, params.credentialId, params.id]); if (changed.changes !== 1) throw new AccessDeniedError(); await db.run('UPDATE recording_download_grants SET revoked_at=COALESCE(revoked_at,?) WHERE credential_id=?', [timestamp, params.credentialId]); await audit(request, context, 'open_platform.credential_revoked', 'application_credential', String(params.credentialId), String(detail.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: params.credentialId, status: 'revoked' }); });

  app.get('/api/v1/open-platform/applications/:id/usage', async (request, reply) => { const context = await resolveAccess(request); const detail = await service.getApplication(context, String((request.params as Row).id)); const buckets = await db.all<Row>('SELECT * FROM application_usage_buckets WHERE application_id=? ORDER BY bucket_start DESC LIMIT 168', [detail.id]); const summary = await db.get<Row>('SELECT COUNT(*) AS request_count,SUM(CASE WHEN status_code>=400 THEN 1 ELSE 0 END) AS error_count,AVG(duration_ms) AS average_duration_ms FROM open_platform_api_logs WHERE application_id=? AND created_at>=?', [detail.id, new Date(Date.now() - 24 * 60 * 60_000).toISOString()]); return success(reply, { summary_24h: summary, buckets }); });
  app.get('/api/v1/open-platform/applications/:id/audit', async (request, reply) => { const context = await resolveAccess(request); const detail = await service.getApplication(context, String((request.params as Row).id)); return success(reply, await db.all<Row>('SELECT id,actor_id,action,resource_type,resource_id,group_id,application_id,credential_id,principal_id,request_id,result,reason,created_at FROM audit_logs WHERE application_id=? OR resource_id=? ORDER BY created_at DESC,id DESC LIMIT 200', [detail.id, detail.id])); });
  app.get('/api/v1/open-platform/call-logs', async (request, reply) => { const context = await resolveAccess(request); if (context.actorType !== 'user' || (!context.isSystemAdmin && !context.isGroupAdmin)) throw new AccessDeniedError(); const params: unknown[] = []; let where = '1=1'; if (!context.isSystemAdmin) { where += ' AND l.application_id IN (SELECT id FROM open_platform_applications WHERE group_id=?)'; params.push(requireGroup(context)); } return success(reply, await db.all<Row>(`SELECT l.* FROM open_platform_api_logs l WHERE ${where} ORDER BY l.created_at DESC,l.id DESC LIMIT 500`, params)); });
  app.get('/api/v1/open-platform/download-grants', async (request, reply) => { const context = await resolveAccess(request); if (context.actorType !== 'user' || (!context.isSystemAdmin && !context.isGroupAdmin)) throw new AccessDeniedError(); const params: unknown[] = []; let where = '1=1'; if (!context.isSystemAdmin) { where += ' AND g.group_id=?'; params.push(requireGroup(context)); } return success(reply, await db.all<Row>(`SELECT g.id,g.file_id,g.device_id,g.group_id,g.application_id,g.credential_id,g.purpose,g.expires_at,g.max_requests,g.request_count,g.first_used_at,g.last_used_at,g.revoked_at,g.created_at FROM recording_download_grants g WHERE ${where} ORDER BY g.created_at DESC,g.id DESC LIMIT 500`, params)); });
  app.delete('/api/v1/open-platform/download-grants/:id', async (request, reply) => { const context = await resolveAccess(request, true); if (context.actorType !== 'user') throw new AccessDeniedError(); const grantId = String((request.params as Row).id); const grant = await db.get<{ group_id: string }>('SELECT group_id FROM recording_download_grants WHERE id=?', [grantId]); if (!grant) throw new AccessDeniedError(); requireGroupAdmin(context, grant.group_id); await db.run('UPDATE recording_download_grants SET revoked_at=COALESCE(revoked_at,?) WHERE id=?', [now(), grantId]); await audit(request, context, 'open_platform.download_grant_revoked', 'recording_download_grant', grantId, grant.group_id, requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: grantId, revoked: true }); });
  app.get('/api/v1/open-platform/security-alerts', async (request, reply) => { const context = await resolveAccess(request); if (context.actorType !== 'user' || (!context.isSystemAdmin && !context.isGroupAdmin)) throw new AccessDeniedError(); const params: unknown[] = []; let where = '1=1'; if (!context.isSystemAdmin) { where += ' AND application_id IN (SELECT id FROM open_platform_applications WHERE group_id=?)'; params.push(requireGroup(context)); } return success(reply, await db.all<Row>(`SELECT * FROM open_platform_security_alerts WHERE ${where} ORDER BY created_at DESC,id DESC LIMIT 200`, params)); });
  app.post('/api/v1/open-platform/security-alerts/:id/resolve', async (request, reply) => { const context = await resolveAccess(request, true); if (context.actorType !== 'user') throw new AccessDeniedError(); const alertId = String((request.params as Row).id); const alert = await db.get<{ application_id: string | null; group_id: string | null }>('SELECT s.application_id,a.group_id FROM open_platform_security_alerts s LEFT JOIN open_platform_applications a ON a.id=s.application_id WHERE s.id=?', [alertId]); if (!alert) throw new AccessDeniedError(); if (!context.isSystemAdmin) requireGroupAdmin(context, String(alert.group_id)); const changed = await db.run("UPDATE open_platform_security_alerts SET status='resolved',resolved_by=?,resolved_at=? WHERE id=? AND status='open'", [context.actorId, now(), alertId]); if (changed.changes !== 1) throw new OpenPlatformError(409, 'ALERT_ALREADY_RESOLVED', 'Security alert is already resolved'); await audit(request, context, 'open_platform.security_alert_resolved', 'open_platform_security_alert', alertId, alert.group_id ?? undefined, requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: alertId, status: 'resolved' }); });

  app.get('/api/v1/open-platform/applications/:id/webhooks', async (request, reply) => { const detail = await service.getApplication(await resolveAccess(request), String((request.params as Row).id)); return success(reply, detail.webhooks); });
  app.post('/api/v1/open-platform/applications/:id/webhooks', async (request, reply) => { const context = await resolveAccess(request, true); const applicationId = String((request.params as Row).id); await service.requireApplicationAccess(context, applicationId, 'developer'); const detail = await service.getApplication(context, applicationId); if (detail.status !== 'active' || !(detail.channels as string[]).includes('webhook') || !(detail.permissions as string[]).includes('events:read')) throw new OpenPlatformError(409, 'WEBHOOK_CHANNEL_UNAVAILABLE', 'The Application must be active with webhook and events:read enabled'); const body = bodyOf(request); const url = await validateWebhookUrl(requiredString(body, 'url', 2000), config.allowPrivateWebhooks, config.allowHttpWebhooks); const eventTypes = body.event_types === undefined ? [] : stringArray(body, 'event_types'); const deviceIds = body.device_ids === undefined ? [] : stringArray(body, 'device_ids'); const attributes = body.attributes === undefined ? [] : numberArray(body, 'attributes'); if (deviceIds.length) { const placeholders = deviceIds.map(() => '?').join(','); const visible = await db.get<{ count: number }>(`SELECT COUNT(*) AS count FROM devices WHERE group_id=? AND deleted_at IS NULL AND id IN (${placeholders})`, [detail.group_id, ...deviceIds]); if (Number(visible?.count ?? 0) !== deviceIds.length) throw new AccessDeniedError(); } const endpointId = id('endpoint'); const secretId = id('secret'); const secret = `vce_${opaqueToken()}`; const timestamp = now(); await db.run('INSERT INTO event_endpoints(id,group_id,application_id,url,secret_id,secret_ciphertext,event_types_json,device_ids_json,attributes_json,updated_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)', [endpointId, detail.group_id, applicationId, url.href, secretId, encryptSecret(secret, config.masterKey, endpointId), JSON.stringify(eventTypes), JSON.stringify(deviceIds), JSON.stringify(attributes), timestamp, timestamp]); await audit(request, context, 'open_platform.webhook_created', 'event_endpoint', endpointId, String(detail.group_id), requiredString(body, 'reason', 256)); reply.header('cache-control', 'private, no-store'); return success(reply, { id: endpointId, application_id: applicationId, secret_id: secretId, secret, filter: { event_types: eventTypes, ...(deviceIds.length ? { device_ids: deviceIds } : {}), ...(attributes.length ? { attributes } : {}) }, filter_version: 1 }, 201); });
  app.patch('/api/v1/open-platform/applications/:id/webhooks/:endpointId', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const applicationId = String(params.id); const detail = await service.requireApplicationAccess(context, applicationId, 'developer'); const current = await db.get<Row>('SELECT * FROM event_endpoints WHERE id=? AND application_id=?', [params.endpointId, applicationId]); if (!current) throw new AccessDeniedError(); const body = bodyOf(request); const url = body.url === undefined ? String(current.url) : (await validateWebhookUrl(requiredString(body, 'url', 2000), config.allowPrivateWebhooks, config.allowHttpWebhooks)).href; const enabled = body.enabled === undefined ? Number(current.enabled) : body.enabled === true ? 1 : body.enabled === false ? 0 : (() => { throw new OpenPlatformError(400, 'INVALID_REQUEST', 'enabled must be boolean'); })(); const eventTypes = body.event_types === undefined ? parseJsonArray(current.event_types_json) : stringArray(body, 'event_types'); const deviceIds = body.device_ids === undefined ? parseJsonArray(current.device_ids_json) : stringArray(body, 'device_ids'); const attributes = body.attributes === undefined ? parseJsonArray(current.attributes_json).map(Number) : numberArray(body, 'attributes'); if (deviceIds.length) { const placeholders = deviceIds.map(() => '?').join(','); const visible = await db.get<{ count: number }>(`SELECT COUNT(*) AS count FROM devices WHERE group_id=? AND deleted_at IS NULL AND id IN (${placeholders})`, [detail.group_id, ...deviceIds]); if (Number(visible?.count ?? 0) !== deviceIds.length) throw new AccessDeniedError(); } const timestamp = now(); await db.run('UPDATE event_endpoints SET url=?,enabled=?,event_types_json=?,device_ids_json=?,attributes_json=?,filter_version=filter_version+1,updated_at=? WHERE id=? AND application_id=?', [url, enabled, JSON.stringify(eventTypes), JSON.stringify(deviceIds), JSON.stringify(attributes), timestamp, params.endpointId, applicationId]); await audit(request, context, 'open_platform.webhook_updated', 'event_endpoint', String(params.endpointId), String(detail.group_id), requiredString(body, 'reason', 256)); return success(reply, { id: params.endpointId, url, enabled: Boolean(enabled), filter: { event_types: eventTypes, ...(deviceIds.length ? { device_ids: deviceIds } : {}), ...(attributes.length ? { attributes } : {}) }, filter_version: Number(current.filter_version ?? 1) + 1, updated_at: timestamp }); });
  app.post('/api/v1/open-platform/applications/:id/webhooks/:endpointId/rotate-secret', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const applicationId = String(params.id); const detail = await service.requireApplicationAccess(context, applicationId, 'developer'); const endpoint = await db.get<{ next_secret_id: string | null }>('SELECT next_secret_id FROM event_endpoints WHERE id=? AND application_id=?', [params.endpointId, applicationId]); if (!endpoint) throw new AccessDeniedError(); if (endpoint.next_secret_id) throw new OpenPlatformError(409, 'SECRET_ROTATION_PENDING', 'A secret rotation is already pending'); const body = bodyOf(request); const activatesAt = optionalString(body, 'activates_at', 64) ?? plus(2 * 60_000); if (!Number.isFinite(Date.parse(activatesAt)) || Date.parse(activatesAt) < Date.now() + 60_000 || Date.parse(activatesAt) > Date.now() + 7 * 24 * 60 * 60_000) throw new OpenPlatformError(400, 'INVALID_ACTIVATION_TIME', 'Activation must be between one minute and seven days from now'); const secretId = id('secret'); const secret = `vce_${opaqueToken()}`; await db.run('UPDATE event_endpoints SET next_secret_id=?,next_secret_ciphertext=?,next_activates_at=? WHERE id=?', [secretId, encryptSecret(secret, config.masterKey, String(params.endpointId)), activatesAt, params.endpointId]); await audit(request, context, 'open_platform.webhook_secret_rotated', 'event_endpoint', String(params.endpointId), String(detail.group_id), requiredString(body, 'reason', 256)); reply.header('cache-control', 'private, no-store'); return success(reply, { id: params.endpointId, secret_id: secretId, secret, activates_at: activatesAt }); });
  app.post('/api/v1/open-platform/applications/:id/webhooks/:endpointId/test', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const application = await service.requireApplicationAccess(context, String(params.id), 'developer'); const endpoint = await db.get<Row>('SELECT * FROM event_endpoints WHERE id=? AND application_id=? AND enabled=1', [params.endpointId, params.id]); if (!endpoint) throw new AccessDeniedError(); const device = await db.get<Row>("SELECT * FROM devices WHERE group_id=? AND deleted_at IS NULL AND claim_status='active' ORDER BY created_at LIMIT 1", [application.group_id]); if (!device) throw new OpenPlatformError(409, 'WEBHOOK_TEST_DEVICE_REQUIRED', 'The Application group has no active device for a scoped test event'); const timestamp = now(); const eventId = id('evt'); const deliveryId = id('delivery'); await db.batch([{ sql: 'INSERT INTO events(id,type,device_id,owner_group_id,ownership_epoch,payload_json,created_at) VALUES(?,?,?,?,?,?,?)', params: [eventId, 'webhook.test', device.id, application.group_id, device.ownership_epoch, JSON.stringify({ test: true, application_id: params.id, endpoint_id: params.endpointId }), timestamp] }, { sql: 'INSERT INTO event_deliveries(id,event_id,endpoint_id,replay_namespace,status,next_attempt_at,created_at) VALUES(?,?,?,?,?,?,?)', params: [deliveryId, eventId, params.endpointId, `test:${eventId}`, 'pending', timestamp, timestamp] }]); await audit(request, context, 'open_platform.webhook_test_sent', 'event_endpoint', String(params.endpointId), String(application.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { event_id: eventId, delivery_id: deliveryId, status: 'pending' }, 202); });
  app.get('/api/v1/open-platform/applications/:id/webhooks/:endpointId/deliveries', async (request, reply) => { const context = await resolveAccess(request); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id)); const endpoint = await db.get<Row>('SELECT id FROM event_endpoints WHERE id=? AND application_id=?', [params.endpointId, params.id]); if (!endpoint) throw new AccessDeniedError(); const status = (request.query as Row).status; const values: unknown[] = [params.endpointId]; let filter = ''; if (status !== undefined) { if (!['pending', 'delivered', 'dead', 'canceled'].includes(String(status))) throw new OpenPlatformError(400, 'INVALID_DELIVERY_STATUS', 'Unsupported delivery status'); filter = ' AND status=?'; values.push(status); } const items = await db.all<Row>(`SELECT id,event_id,replay_namespace,status,attempts,next_attempt_at,delivered_at,last_status_code,last_error,created_at FROM event_deliveries WHERE endpoint_id=?${filter} ORDER BY created_at DESC,id DESC LIMIT 200`, values); const health = await db.get<Row>("SELECT MIN(CASE WHEN status='pending' THEN created_at END) AS oldest_pending_at,MIN(CASE WHEN status='dead' THEN created_at END) AS oldest_dead_at,MAX(delivered_at) AS last_success_at FROM event_deliveries WHERE endpoint_id=?", [params.endpointId]); return success(reply, { items, health }); });
  app.post('/api/v1/open-platform/applications/:id/webhook-deliveries/:deliveryId/replay', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const application = await service.requireApplicationAccess(context, String(params.id), 'developer'); const source = await db.get<Row>(`SELECT ed.*,ep.application_id FROM event_deliveries ed JOIN event_endpoints ep ON ep.id=ed.endpoint_id WHERE ed.id=? AND ep.application_id=?`, [params.deliveryId, params.id]); if (!source) throw new AccessDeniedError(); if (!['dead', 'canceled'].includes(String(source.status))) throw new OpenPlatformError(409, 'DELIVERY_NOT_REPLAYABLE', 'Only dead or canceled deliveries can be replayed'); const replayNamespace = `manual:${id('replay')}`; const deliveryId = id('delivery'); const timestamp = now(); await db.run('INSERT INTO event_deliveries(id,event_id,endpoint_id,replay_namespace,status,next_attempt_at,created_at) VALUES(?,?,?,?,?,?,?)', [deliveryId, source.event_id, source.endpoint_id, replayNamespace, 'pending', timestamp, timestamp]); await audit(request, context, 'open_platform.webhook_delivery_replayed', 'event_delivery', String(params.deliveryId), String(application.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: deliveryId, original_delivery_id: params.deliveryId, event_id: source.event_id, replay_namespace: replayNamespace, status: 'pending' }, 202); });
  const applicationBackfillEvents = async (endpoint: Row, body: Row): Promise<Row[]> => { const from = optionalString(body, 'from_created_at', 64); const to = optionalString(body, 'to_created_at', 64); if (from && !Number.isFinite(Date.parse(from))) throw new OpenPlatformError(400, 'INVALID_TIME_RANGE', 'from_created_at is invalid'); if (to && !Number.isFinite(Date.parse(to))) throw new OpenPlatformError(400, 'INVALID_TIME_RANGE', 'to_created_at is invalid'); if (from && to && from > to) throw new OpenPlatformError(400, 'INVALID_TIME_RANGE', 'from_created_at must not be after to_created_at'); const requestedTypes = body.event_types === undefined ? parseJsonArray(endpoint.event_types_json) : stringArray(body, 'event_types'); const deviceIds = parseJsonArray(endpoint.device_ids_json); const attributes = parseJsonArray(endpoint.attributes_json).map(Number); const values: unknown[] = [endpoint.group_id, endpoint.group_id]; let filter = ''; if (from) { filter += ' AND e.created_at>=?'; values.push(from); } if (to) { filter += ' AND e.created_at<=?'; values.push(to); } const rows = await db.all<Row>(`SELECT e.* FROM events e JOIN devices d ON d.id=e.device_id WHERE d.group_id=? AND e.owner_group_id=? AND e.ownership_epoch=d.ownership_epoch${filter} ORDER BY e.created_at,e.id LIMIT 1001`, values); const filtered = rows.filter((event) => { const payload = JSON.parse(String(event.payload_json)) as Row; return (requestedTypes.length === 0 || requestedTypes.includes(String(event.type))) && (deviceIds.length === 0 || deviceIds.includes(String(event.device_id))) && (attributes.length === 0 || (typeof payload.attribute === 'number' && attributes.includes(payload.attribute))); }); if (filtered.length > 1000) throw new OpenPlatformError(409, 'BACKFILL_TOO_LARGE', 'Backfill is limited to 1000 events'); return filtered; };
  app.post('/api/v1/open-platform/applications/:id/webhooks/:endpointId/backfill-preview', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; await service.requireApplicationAccess(context, String(params.id), 'developer'); const endpoint = await db.get<Row>('SELECT * FROM event_endpoints WHERE id=? AND application_id=? AND enabled=1', [params.endpointId, params.id]); if (!endpoint) throw new AccessDeniedError(); const body = bodyOf(request); const events = await applicationBackfillEvents(endpoint, body); const version = `${endpoint.filter_version}:${events.length}:${events.at(-1)?.id ?? ''}`; const confirmation = tokenHash(JSON.stringify({ endpoint_id: params.endpointId, from: body.from_created_at ?? null, to: body.to_created_at ?? null, types: body.event_types ?? null, version }), config.masterKey); return success(reply, { endpoint_id: params.endpointId, event_count: events.length, resource_version: version, confirmation_token: confirmation }); });
  app.post('/api/v1/open-platform/applications/:id/webhooks/:endpointId/backfill', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const application = await service.requireApplicationAccess(context, String(params.id), 'developer'); const endpoint = await db.get<Row>('SELECT * FROM event_endpoints WHERE id=? AND application_id=? AND enabled=1', [params.endpointId, params.id]); if (!endpoint) throw new AccessDeniedError(); const body = bodyOf(request); const events = await applicationBackfillEvents(endpoint, body); const version = `${endpoint.filter_version}:${events.length}:${events.at(-1)?.id ?? ''}`; const confirmation = tokenHash(JSON.stringify({ endpoint_id: params.endpointId, from: body.from_created_at ?? null, to: body.to_created_at ?? null, types: body.event_types ?? null, version }), config.masterKey); if (requiredString(body, 'resource_version', 200) !== version || requiredString(body, 'confirmation_token', 200) !== confirmation) throw new OpenPlatformError(409, 'BACKFILL_PREVIEW_STALE', 'Backfill preview is stale'); const replayId = id('replay'); const timestamp = now(); const statements: SqlStatement[] = [{ sql: 'INSERT INTO event_replays(id,group_id,endpoint_id,from_created_at,to_created_at,event_type,requested_by,created_at) VALUES(?,?,?,?,?,?,?,?)', params: [replayId, endpoint.group_id, params.endpointId, body.from_created_at ?? null, body.to_created_at ?? null, Array.isArray(body.event_types) ? JSON.stringify(body.event_types) : null, context.actorId, timestamp] }]; for (const event of events) statements.push({ sql: 'INSERT INTO event_deliveries(id,event_id,endpoint_id,replay_namespace,status,next_attempt_at,created_at) VALUES(?,?,?,?,?,?,?)', params: [id('delivery'), event.id, params.endpointId, replayId, 'pending', timestamp, timestamp] }); await db.batch(statements); await audit(request, context, 'open_platform.webhook_backfilled', 'event_replay', replayId, String(application.group_id), requiredString(body, 'reason', 256)); return success(reply, { id: replayId, event_count: events.length }, 202); });
  app.delete('/api/v1/open-platform/applications/:id/webhooks/:endpointId', async (request, reply) => { const context = await resolveAccess(request, true); const params = request.params as Row; const applicationId = String(params.id); const detail = await service.requireApplicationAccess(context, applicationId, 'developer'); const changed = await db.run('UPDATE event_endpoints SET enabled=0 WHERE id=? AND application_id=?', [params.endpointId, applicationId]); if (changed.changes !== 1) throw new AccessDeniedError(); await db.run("UPDATE event_deliveries SET status='canceled',last_error='ENDPOINT_DISABLED',claimed_by=NULL,claim_expires_at=NULL WHERE endpoint_id=? AND status='pending'", [params.endpointId]); await audit(request, context, 'open_platform.webhook_disabled', 'event_endpoint', String(params.endpointId), String(detail.group_id), requiredString(bodyOf(request), 'reason', 256)); return success(reply, { id: params.endpointId, enabled: false }); });

  app.get('/api/v1/capabilities', async (request, reply) => success(reply, await service.capabilities(await resolveAccess(request))));
  app.get('/api/v1/devices/:id/capabilities', async (request, reply) => success(reply, await service.getDeviceCapabilities(await resolveAccess(request), String((request.params as Row).id))));
  app.get('/api/v1/devices/:id/commands', async (request, reply) => success(reply, await service.listDeviceCommands(await resolveAccess(request), String((request.params as Row).id))));
  app.get('/api/v1/recordings', async (request, reply) => success(reply, await service.listRecordings(await resolveAccess(request), request.query as Row)));
  app.get('/api/v1/recordings/:id', async (request, reply) => success(reply, await service.getRecording(await resolveAccess(request), String((request.params as Row).id))));
  app.post('/api/v1/recordings/:id/download-links', async (request, reply) => { const context = await resolveAccess(request, true); const body = bodyOf(request); const reason = requiredString(body, 'reason', 256); const result = await service.createDownloadLink(context, String((request.params as Row).id), { ...(body.ttl_seconds === undefined ? {} : { ttlSeconds: integer(body, 'ttl_seconds', config.downloadGrantDefaultTtlSeconds, config.downloadGrantMinTtlSeconds, config.downloadGrantMaxTtlSeconds) }), ...(body.purpose === undefined ? {} : { purpose: requiredString(body, 'purpose', 32) }), idempotencyKey: String(request.headers['idempotency-key'] ?? '') }); await audit(request, context, 'recording.download_grant_created', 'recording_download_grant', result.grant_id, context.groupId ?? undefined, reason); reply.header('cache-control', 'private, no-store'); return success(reply, result, 201); });
  app.delete('/api/v1/recording-download-links/:id', async (request, reply) => { const context = await resolveAccess(request, true); const result = await service.revokeDownloadLink(context, String((request.params as Row).id)); await audit(request, context, 'recording.download_grant_revoked', 'recording_download_grant', result.grant_id); return success(reply, result); });
  app.get('/api/v1/recording-download-grants/:id', async (request, reply) => success(reply, await service.getDownloadGrant(await resolveAccess(request), String((request.params as Row).id))));
  app.post('/api/v1/recording-download-grants/:id/revoke', async (request, reply) => { const context = await resolveAccess(request, true); const reason = requiredString(bodyOf(request), 'reason', 256); const result = await service.revokeDownloadLink(context, String((request.params as Row).id)); await audit(request, context, 'recording.download_grant_revoked', 'recording_download_grant', result.grant_id, context.groupId ?? undefined, reason); return success(reply, result); });
  app.get('/recording-download/v1/:token', async (request, reply) => service.consumeDownload(request, reply, String((request.params as Row).token)));

  return service;
}
