import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('React Admin preserves guarded lifecycle, Open Platform, inspector, and end-user resource management', async () => {
  const app = await readFile(new URL('../../admin-web/src/App.tsx', import.meta.url), 'utf8');
  const workspaces = await readFile(new URL('../../admin-web/src/workspaces.tsx', import.meta.url), 'utf8');
  const openPlatform = await readFile(new URL('../../admin-web/src/open-platform-workspace.tsx', import.meta.url), 'utf8');
  const deviceIntegration = await readFile(new URL('../../admin-web/src/device-integration.tsx', import.meta.url), 'utf8');
  const deviceManagement = await readFile(new URL('../../admin-web/src/device-management.tsx', import.meta.url), 'utf8');
  const connectProtocol = await readFile(new URL('../../device-connect-web/src/protocol.ts', import.meta.url), 'utf8');
  const connectPage = await readFile(new URL('../../device-connect-web/src/main.ts', import.meta.url), 'utf8');
  const ui = await readFile(new URL('../../admin-web/src/ui.tsx', import.meta.url), 'utf8');
  const style = await readFile(new URL('../../admin-web/src/style.css', import.meta.url), 'utf8');
  const directDeviceUi = await readFile(new URL('../src/ui.ts', import.meta.url), 'utf8');
  const implementation = `${app}\n${workspaces}\n${ui}\n${deviceIntegration}`;
  const i18n = await readFile(new URL('../../admin-web/src/i18n.ts', import.meta.url), 'utf8');
  const api = await readFile(new URL('../../admin-web/src/api.ts', import.meta.url), 'utf8');
  const vite = await readFile(new URL('../../admin-web/vite.config.ts', import.meta.url), 'utf8');
  assert.match(implementation, /Delivery ID to replay/);
  assert.doesNotMatch(implementation, /VOICECAN_SIMULATOR=true|simulator\/files|Developer tools/);
  assert.match(implementation, /event-deliveries\/.*\/replay/);
  assert.match(api, /x-csrf-token/);
  assert.match(vite, /base: '\/admin\/'/);
  assert.match(app, /voicecan\.locale|initialLocale/);
  assert.match(i18n, /'Devices': '设备'/);
  assert.match(i18n, /'zh-CN' \| 'en'/);
  assert.match(app, /navGroups/);
  assert.match(app, /URLSearchParams/);
  assert.match(app, /popstate/);
  assert.match(app, /pushState/);
  assert.match(implementation, /Stepper/);
  assert.match(implementation, /ResourcePicker/);
  assert.match(implementation, /EmbeddedDeviceProvisioner/);
  assert.match(implementation, /RemoteDeviceProvisioner/);
  assert.match(implementation, /supportsLocalWebBluetooth/);
  assert.match(implementation, /provision-device-ws-url/);
  assert.match(workspaces, /preferred_device_ws_url/);
  assert.match(workspaces, /device_ws_urls/);
  assert.match(workspaces, /DeviceWsCandidatePicker candidates=\{deviceWsCandidates\}/);
  assert.match(workspaces, /setDeviceWsUrl\(\(currentUrl\) => currentUrl \|\| settings\.preferred_device_ws_url\)/);
  assert.match(deviceManagement, /DeviceWsCandidatePicker candidates=\{serverCandidates\}/);
  assert.match(ui, /aria-pressed=\{value === candidate\.url\}/);
  assert.match(workspaces, /Use an address reachable from the device network/);
  assert.doesNotMatch(workspaces, /placeholder="ws:\/\/192\.168\.1\.100/);
  assert.match(implementation, /Device access settings/);
  assert.match(implementation, /ble-name-prefix/);
  assert.match(implementation, /save-device-access-settings/);
  assert.match(implementation, /settings\/device-access/);
  assert.match(implementation, /Runtime capacity policy/);
  assert.match(implementation, /save-storage-settings/);
  assert.match(implementation, /driver_change_requires_restart/);
  assert.match(app, /Use user groups to assign devices and recordings to a shared access boundary/);
  assert.match(deviceIntegration, /device_ws_url/);
  assert.match(deviceIntegration, /observeOnline/);
  assert.match(deviceIntegration, /DEVICE_ALREADY_CLAIMED/);
  assert.match(deviceIntegration, /onAlreadyClaimed/);
  assert.match(deviceIntegration, /resolveAccessibleClaimedDeviceId/);
  assert.match(deviceIntegration, /api<Array<Readonly<Record<string, unknown>>>>\('\/devices'\)/);
  assert.match(deviceManagement, /if \(requested\)[\s\S]*requested !== deviceId/);
  assert.match(deviceManagement, /current && !items\.some/);
  assert.match(deviceIntegration, /Voicecan Provisioning/);
  assert.match(deviceIntegration, /compact: true/);
  assert.match(deviceIntegration, /bleNamePrefix/);
  assert.doesNotMatch(workspaces, /FlowHeader eyebrow=\{t\('Device onboarding'\)\}/);
  assert.match(deviceIntegration, /new MessageChannel\(\)/);
  assert.match(deviceIntegration, /globalThis\.open\('about:blank'[^]*await createGrant\(\)/);
  assert.match(workspaces, /connector_origin: new URL\(connectorUrl\)\.origin/);
  assert.match(deviceIntegration, /当前管理页不是安全上下文/);
  assert.match(deviceIntegration, /当前浏览器没有提供 Web Bluetooth/);
  assert.match(deviceIntegration, /重新打开配对页/);
  assert.match(deviceIntegration, /reusableGrantRef/);
  assert.match(deviceIntegration, /event\.origin !== publicUrl\.origin/);
  assert.match(deviceIntegration, /popup\.postMessage\(init, publicUrl\.origin/);
  assert.match(app, /decodeConnectCallback/);
  assert.match(app, /url\.searchParams\.set\('device', deviceId\)/);
  assert.match(app, /onNavigateDevice=\{selectDevice\}/);
  assert.match(app, /voicecan\.connect\.state/);
  assert.match(app, /\/provisioning-sessions\/\$\{encodeURIComponent\(pendingConnectReturn\.provisioningSessionId\)\}/);
  assert.match(connectProtocol, /globalThis\.isSecureContext/);
  assert.match(connectPage, /globalThis\.location\.replace/);
  assert.doesNotMatch(connectPage, /provisioning_token|localStorage/);
  assert.match(implementation, /startProvisioning/);
  assert.match(workspaces, /selectFirst/);
  assert.match(workspaces, /Start binding/);
  assert.doesNotMatch(workspaces, /Create 10-minute binding grant/);
  assert.doesNotMatch(ui, /View raw response|raw-result/);
  assert.match(ui, /table-pagination/);
  assert.match(workspaces, /User list/);
  assert.match(directDeviceUi, /DEVICE_ALREADY_CLAIMED/);
  assert.match(directDeviceUi, /view=devices&device=/);
  assert.match(style, /--vc-bg: #f7f6f2/);
  assert.match(style, /\.embedded-device-flow\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(style, /\.remote-connect-card\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(style, /prefers-reduced-motion/);
  assert.match(openPlatform, /method: 'DELETE'/);
  assert.match(openPlatform, /Archive application/);
  assert.doesNotMatch(openPlatform, /\['active', 'suspended', 'archived'\]/);
  assert.doesNotMatch(workspaces, /Legacy integrations|TokensWorkspace|WebhooksWorkspace|ApiWorkspace/);
  assert.match(workspaces, /Open platform/);
  assert.match(openPlatform, /Create credential/);
  assert.match(openPlatform, /Create webhook/);
  for (const control of ['create-user', 'update-user', 'create-group', 'transfer-group-admin']) {
    assert.match(implementation, new RegExp(`id="${control}"`));
  }
});

test('public Device UI uses Lit while retaining the Custom Element contract', async () => {
  const source = await readFile(new URL('../../device-ui/src/index.ts', import.meta.url), 'utf8');
  const i18n = await readFile(new URL('../../device-ui/src/i18n.ts', import.meta.url), 'utf8');
  assert.match(source, /extends LitElement/);
  assert.doesNotMatch(source, /innerHTML\s*=/);
  for (const element of ['voicecan-provisioner', 'voicecan-device-console', 'voicecan-transfer-out']) assert.match(source, new RegExp(`'${element}'`));
  for (const event of ['provisioned', 'provisionerror', 'syncrequest', 'released', 'releaseerror']) assert.match(source, new RegExp(`'${event}'`));
  assert.match(source, /requestUpdate\('locale', previous\)/);
  assert.doesNotMatch(source, /protected (?:statusMessage|busy|busyAction|step|networkError|acknowledged)\s*=/, 'Lit reactive accessors must not be shadowed by native class fields');
  assert.match(source, /declare protected step: number/);
  assert.match(source, /class="stepper"/);
  assert.match(source, /class="connection-visual"/);
  assert.match(source, /class="device-beacon"/);
  assert.match(source, /class="stage device-overview"/);
  assert.match(source, /class="telemetry-grid"/);
  assert.match(source, /class="waiting-telemetry-grid"/);
  assert.match(source, /class="provisioning-device-snapshot"/);
  assert.match(source, /provisioningclaim/);
  assert.match(source, /deviceinfo/);
  assert.match(source, /devicestatus/);
  assert.match(source, /#refreshLiveStatus/);
  assert.match(source, /3_000/);
  assert.match(source, /this\.step === 1 \|\| this\.step === 2 \|\| this\.step === 3/);
  assert.match(source, /@keyframes orbit-turn/);
  assert.match(source, /aria-live="polite"/);
  assert.match(source, /prefers-reduced-motion/);
  assert.match(source, /Use the same network as the server/);
  assert.match(source, /Connect & bind/);
  assert.match(source, /Choose device and bind/);
  assert.match(source, /Token binding is complete/);
  assert.match(source, /Current network status/);
  assert.match(source, /Keep network and continue/);
  assert.match(source, /completeProvisioning/);
  assert.match(source, /this\.compact \? nothing/);
  assert.match(source, /this\.step < 2 && \(!this\.compact \|\| this\.step === 1\)/);
  assert.match(i18n, /'Bind Voicecan device': '绑定 Voicecan 设备'/);
  assert.match(i18n, /'Device binding grant': '设备绑定凭证'/);
  assert.match(i18n, /'Connect & bind': '连接并绑定'/);
  assert.match(i18n, /'Keep network and continue': '保留网络并继续'/);
  assert.match(i18n, /'configuring server': '网络已可用，正在设置服务器地址'/);
  assert.match(i18n, /'Status updated at \{time\}': '状态更新于 \{time\}'/);
  assert.match(i18n, /'Device storage': '设备存储'/);
  assert.match(i18n, /'\{free\} free of \{total\}': '\{free\} 可用，共 \{total\}'/);
  assert.match(i18n, /'\{hours\} h estimated recording time': '预计可录音 \{hours\} 小时'/);
  assert.match(i18n, /'必须与服务器处于同一个网络'/);
});
