import assert from 'node:assert/strict';
import { createHash, generateKeyPairSync, randomBytes, randomUUID, sign } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { buildServer } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { DatabaseActor } from '../src/database.js';
import { migrate } from '../src/migrate.js';
import { nativeProofMessage } from '../src/native-handoff.js';

const audience = 'http://127.0.0.1:8787';
const taskAudience = 'http://192.168.50.20:8787';
test('native handoff: proof, Web approval, fencing, same-token recovery and authoritative completion', async (t) => {
  const dataDir = await mkdtemp(join(tmpdir(), 'voicecan-native-'));
  const config = await loadConfig({ VOICECAN_DATA_DIR: dataDir, VOICECAN_PUBLIC_BASE_URL: audience, VOICECAN_DEVICE_ADVERTISE_HOST: '192.168.50.20', VOICECAN_BLE_SERVICE_UUID: '1a12', VOICECAN_LOG_LEVEL: 'silent' });
  migrate(config);
  const db = new DatabaseActor(config.databaseFile);
  const app = await buildServer(config, { database: db });
  t.after(async () => { await app.close(); await rm(dataDir, { recursive: true, force: true }); });
  const setup = await app.inject({ method: 'POST', url: '/api/v1/setup/admin', payload: { setup_token: (await readFile(join(dataDir, 'setup-token'), 'utf8')).trim(), username: 'admin', password: 'correct horse battery staple' } });
  assert.equal(setup.statusCode, 201, setup.body);
  const login = await app.inject({ method: 'POST', url: '/api/v1/auth/login', payload: { username: 'admin', password: 'correct horse battery staple' } });
  const headers = { cookie: String(login.headers['set-cookie']).split(';')[0]!, 'x-csrf-token': login.json().data.csrf_token as string };
  const created = await app.inject({ method: 'POST', url: '/api/v1/binding-intents', headers, payload: { group_id: setup.json().data.group_id, allowed_origin: audience, device_ws_url: `${taskAudience.replace('http:', 'ws:')}/device/v1/ws`, expected_sn: 'NATIVE-0001' } });
  assert.equal(created.statusCode, 201, created.body);
  const intentId = created.json().data.id as string;
  const browserExchange = await app.inject({ method: 'POST', url: '/api/v1/binding-intents/exchange', headers: { origin: audience }, payload: { launch_token: new URLSearchParams(new URL(created.json().data.launch_url).hash.slice(1)).get('launch') } });
  assert.equal(browserExchange.statusCode, 200, browserExchange.body);
  const browserHeaders = { cookie: String(browserExchange.headers['set-cookie']).split(';')[0]!, origin: audience };
  const createPath = `/api/v1/binding-intents/${intentId}/native-handoffs`;
  assert.equal((await app.inject({ method: 'POST', url: createPath, headers: { cookie: browserHeaders.cookie }, payload: {} })).statusCode, 403);
  const makeHandoff = async (targetIntent = intentId) => {
    const response = await app.inject({ method: 'POST', url: `/api/v1/binding-intents/${targetIntent}/native-handoffs`, headers: targetIntent === intentId ? browserHeaders : headers, payload: {} });
    assert.equal(response.statusCode, 201, response.body);
    const data = response.json().data;
    const url = new URL(data.launch_url);
    assert.equal(url.origin, taskAudience, 'native task uses the HTTP origin derived from the selected device WebSocket URL');
    assert.equal(url.searchParams.has('ticket'), false);
    assert.ok(Date.parse(data.ticket_expires_at) - Date.now() <= 300_000);
    return { id: data.handoff_id as string, ticket: new URLSearchParams(url.hash.slice(1)).get('ticket')! };
  };
  const key = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
  const encodedKey = key.publicKey.export({ type: 'spki', format: 'der' }).toString('base64url');
  const proof = (url: string, payload: Record<string, unknown>, signingKey = key.privateKey) => {
    const timestamp = String(Date.now()), nonce = randomBytes(24).toString('base64url');
    return { 'x-vc-timestamp': timestamp, 'x-vc-nonce': nonce, 'x-vc-signature': sign('sha256', Buffer.from(nativeProofMessage(taskAudience, url, timestamp, nonce, payload)), signingKey).toString('base64url') };
  };
  const post = (url: string, payload: Record<string, unknown>) => app.inject({ method: 'POST', url, payload, headers: proof(url, payload) });
  const handoff = await makeHandoff();
  const exchangePath = '/api/v1/native-handoffs/exchange';
  const exchangeBody = { handoff_id: handoff.id, ticket: handoff.ticket, client_public_key: encodedKey, request_id: randomUUID() };
  const exchangeHeaders = proof(exchangePath, exchangeBody);
  const exchanged = await app.inject({ method: 'POST', url: exchangePath, headers: exchangeHeaders, payload: exchangeBody });
  assert.equal(exchanged.statusCode, 200, exchanged.body);
  assert.equal(exchanged.json().data.status, 'exchanged');
  assert.equal(exchanged.json().data.audience, taskAudience);
  assert.equal(exchanged.json().data.instance_id, `instance_${createHash('sha256').update(taskAudience).digest('hex').slice(0, 32)}`);
  assert.equal(exchanged.json().data.callback_registration.url, `${taskAudience}/admin?view=provision&binding_intent=${intentId}`);
  assert.equal('device_token' in exchanged.json().data, false);
  assert.equal((await app.inject({ method: 'POST', url: exchangePath, headers: exchangeHeaders, payload: exchangeBody })).json().code, 'NATIVE_PROOF_REPLAY');
  assert.equal((await post(exchangePath, exchangeBody)).statusCode, 200, 'lost exchange response is recoverable');
  assert.equal((await post(exchangePath, { ...exchangeBody, request_id: randomUUID() })).json().code, 'NATIVE_TICKET_USED');
  const otherKey = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
  const substituted = { ...exchangeBody, client_public_key: otherKey.publicKey.export({ format: 'der', type: 'spki' }).toString('base64url') };
  assert.equal((await app.inject({ method: 'POST', url: exchangePath, payload: substituted, headers: proof(exchangePath, substituted, otherKey.privateKey) })).json().code, 'NATIVE_TICKET_USED');
  const action = (operation: string, payload: Record<string, unknown> = {}, epoch = 1) => post(`/api/v1/native-handoffs/${handoff.id}/${operation}`, { request_id: randomUUID(), execution_epoch: epoch, ...payload });
  const identity = { manufacturer: 'Voicecan', serial_number: 'NATIVE-0001' };
  assert.equal((await action('claim', identity, 0)).statusCode, 409);
  const approvePath = `/api/v1/native-handoffs/${handoff.id}/approve`;
  assert.equal((await app.inject({ method: 'POST', url: approvePath, headers: { cookie: headers.cookie }, payload: { expected_execution_epoch: 0 } })).statusCode, 403, 'admin approval requires CSRF');
  const approve = (epoch: number) => app.inject({ method: 'POST', url: approvePath, headers: browserHeaders, payload: { expected_execution_epoch: epoch } });
  const approved = await approve(0);
  assert.equal(approved.statusCode, 200, approved.body);
  assert.equal(approved.json().data.execution_epoch, 1);
  assert.equal((await approve(0)).json().data.execution_epoch, 1, 'approval retry does not rotate epoch');
  assert.equal((await action('observe', {}, 0)).json().data.execution_epoch, 1, 'observer discovers approval epoch');
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/binding-intents/${intentId}/grant`, headers: browserHeaders, payload: {} })).json().code, 'NATIVE_EXECUTOR_ACTIVE');
  assert.equal((await action('claim', { ...identity, serial_number: 'WRONG' })).json().code, 'NATIVE_TARGET_MISMATCH');
  assert.equal((await action('claim', { ...identity, device_ws_url: 'ws://attacker.invalid/' })).statusCode, 400, 'native cannot replace platform configuration');
  const claimBody = { ...identity, request_id: randomUUID(), execution_epoch: 1 };
  const claimPath = `/api/v1/native-handoffs/${handoff.id}/claim`;
  const forged = proof(claimPath, claimBody, otherKey.privateKey);
  assert.equal((await app.inject({ method: 'POST', url: claimPath, payload: claimBody, headers: forged })).statusCode, 401);
  assert.equal((await app.inject({ method: 'POST', url: claimPath, payload: claimBody, headers: { ...proof(claimPath, claimBody), origin: audience } })).statusCode, 403);
  const concurrent = await Promise.all([post(claimPath, claimBody), post(claimPath, claimBody)]);
  const claimed = concurrent.find(result => result.statusCode === 201)!;
  assert.ok(claimed, 'one concurrent claim creates the credential');
  assert.ok(concurrent.every(result => [200, 201, 409].includes(result.statusCode)));
  assert.equal(claimed.statusCode, 201, claimed.body);
  const retry = await post(claimPath, claimBody);
  assert.equal(retry.statusCode, 200, retry.body);
  assert.equal(retry.json().data.device_token, claimed.json().data.device_token);
  assert.equal('continuation_token' in claimed.json().data, false);
  assert.equal((await post(claimPath, { ...claimBody, model: 'changed' })).json().code, 'NATIVE_IDEMPOTENCY_CONFLICT');
  assert.equal((await db.get<{ count: number }>('SELECT COUNT(*) AS count FROM device_credentials'))?.count, 1);
  const alternateGrant = await app.inject({ method: 'POST', url: '/api/v1/provisioning-sessions', headers, payload: { group_id: setup.json().data.group_id, allowed_origin: audience, expected_sn: identity.serial_number } });
  const stealing = await app.inject({ method: 'POST', url: '/api/v1/provisioning-sessions/claim', headers: { origin: audience }, payload: { ...identity, provisioning_token: alternateGrant.json().data.provisioning_token } });
  assert.equal(stealing.statusCode, 409, 'another task cannot supersede an active native credential owner');
  const rival = await makeHandoff();
  assert.equal((await post(exchangePath, { handoff_id: rival.id, ticket: rival.ticket, client_public_key: encodedKey, request_id: randomUUID() })).statusCode, 200);
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/native-handoffs/${rival.id}/approve`, headers, payload: { expected_execution_epoch: 1 } })).json().code, 'EXECUTOR_ALREADY_STARTED');
  await db.run('UPDATE native_handoffs SET lease_expires_at=? WHERE id=?', [new Date(Date.now() - 1_000).toISOString(), handoff.id]);
  assert.equal((await action('resume')).json().code, 'NATIVE_EXECUTION_CONFLICT');
  assert.equal((await post(claimPath, claimBody)).json().code, 'NATIVE_EXECUTION_CONFLICT');
  assert.equal((await action('observe')).statusCode, 200, 'expired lease remains observable');
  assert.equal((await approve(1)).json().data.execution_epoch, 2);
  assert.equal((await action('claim', identity)).statusCode, 409, 'old epoch is fenced');
  assert.equal((await action('claim', identity, 2)).json().data.device_token, claimed.json().data.device_token, 'reapproval recovers same token');
  assert.equal((await action('progress', { stage: 'completed' }, 2)).statusCode, 400);
  assert.equal((await action('progress', { stage: 'configured' }, 2)).statusCode, 409);
  for (const stage of ['ble_authenticated', 'configured', 'ble_authenticated']) assert.equal((await action('progress', { stage }, 2)).statusCode, 200);
  const cancelled = await action('cancel', {}, 2);
  assert.equal(cancelled.statusCode, 200, cancelled.body);
  assert.equal(cancelled.json().data.binding_status, 'configured');
  assert.equal((await action('claim', identity, 2)).statusCode, 409);
  assert.equal((await db.get<{ count: number }>('SELECT COUNT(*) AS count FROM device_credentials WHERE revoked_at IS NULL'))?.count, 1);
  // Simulate the gateway's already-tested authoritative persistence, not a client completion callback.
  await db.run("UPDATE provisioning_sessions SET status='completed',completed_at=? WHERE device_id=?", [new Date().toISOString(), claimed.json().data.device_id]);
  const final = await action('observe', {}, 2);
  assert.equal(final.json().data.binding_status, 'completed');
  assert.equal((await action('cancel', {}, 2)).json().data.binding_status, 'completed');
  const outsider = await app.inject({ method: 'POST', url: '/api/v1/users', headers, payload: { username: 'outsider', password: 'another long password', role: 'user' } });
  assert.equal(outsider.statusCode, 201, outsider.body);
  const outsiderLogin = await app.inject({ method: 'POST', url: '/api/v1/auth/login', payload: { username: 'outsider', password: 'another long password' } });
  const outsiderHeaders = { cookie: String(outsiderLogin.headers['set-cookie']).split(';')[0]!, 'x-csrf-token': outsiderLogin.json().data.csrf_token as string };
  for (const id of [handoff.id, 'missing']) {
    const response = await app.inject({ method: 'POST', url: `/api/v1/native-handoffs/${id}/approve`, headers: outsiderHeaders, payload: { expected_execution_epoch: 2 } });
    assert.equal(response.statusCode, 404); assert.equal(response.json().code, 'NOT_FOUND'); assert.equal(response.json().message, 'Resource not found');
  }
  const nextIntent = await app.inject({ method: 'POST', url: '/api/v1/binding-intents', headers, payload: { group_id: setup.json().data.group_id, allowed_origin: audience } });
  const competing = await Promise.all([makeHandoff(nextIntent.json().data.id), makeHandoff(nextIntent.json().data.id)]);
  for (const candidate of competing) assert.equal((await post(exchangePath, { handoff_id: candidate.id, ticket: candidate.ticket, client_public_key: encodedKey, request_id: randomUUID() })).statusCode, 200);
  const approvals = await Promise.all(competing.map(candidate => app.inject({ method: 'POST', url: `/api/v1/native-handoffs/${candidate.id}/approve`, headers, payload: { expected_execution_epoch: 0 } })));
  assert.deepEqual(approvals.map(response => response.statusCode).sort(), [200, 409], 'only one competing approval commits');
  const winner = competing[approvals.findIndex(response => response.statusCode === 200)]!;
  const loser = competing.find(candidate => candidate.id !== winner.id)!;
  assert.equal((await post(`/api/v1/native-handoffs/${loser.id}/claim`, { ...identity, request_id: randomUUID(), execution_epoch: 0 })).statusCode, 409);
  const takeover = await app.inject({ method: 'POST', url: `/api/v1/native-handoffs/${loser.id}/approve`, headers, payload: { expected_execution_epoch: 1 } });
  assert.equal(takeover.statusCode, 200, takeover.body);
  assert.equal(takeover.json().data.execution_epoch, 2);
  assert.equal((await post(`/api/v1/native-handoffs/${winner.id}/resume`, { request_id: randomUUID(), execution_epoch: 1 })).statusCode, 409);
  const takeBack = await app.inject({ method: 'POST', url: `/api/v1/native-handoffs/${winner.id}/approve`, headers, payload: { expected_execution_epoch: 2 } });
  assert.equal(takeBack.statusCode, 200, takeBack.body);
  assert.equal((await post(`/api/v1/native-handoffs/${winner.id}/claim`, { manufacturer: 'Voicecan', serial_number: 'NATIVE-0002', request_id: randomUUID(), execution_epoch: 3 })).statusCode, 201, 'an unconsumed superseded session can be reauthorized');
  const stale = await makeHandoff(nextIntent.json().data.id);
  await db.run('UPDATE native_handoffs SET ticket_expires_at=? WHERE id=?', [new Date(Date.now() - 1_000).toISOString(), stale.id]);
  assert.equal((await post(exchangePath, { handoff_id: stale.id, ticket: stale.ticket, client_public_key: encodedKey, request_id: randomUUID() })).json().code, 'NATIVE_TICKET_EXPIRED');
  const preview = await app.inject({ method: 'GET', url: '/native/connect?v=1&handoff=unused' });
  assert.equal(preview.statusCode, 200);
});
